### ISSUE TITLE
Support for FAT32 disk image access from the DOSBox-X shell

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1547]
As mentioned in the discussion of pull request #1544, right now DOSBox-X's support for the FAT32 file system in disk images is very limited, i.e. it does allow FAT32 disk image to boot with a real DOS, but there is no direct support for it from the DOSBox-X shell at all. As a result, DOSBox-X cannot create or access any disk images that are greater than 2GB (or any FAT32 disk images that are between 512MB and 2GB), which (significantly) limits the usefulness of its FAT support. Also, without direct support for FAT32 drives the MS-DOS 7.1+ functions for FAT32 file system cannot be properly implemented either.

Since FAT32 has become a critically important file system for DOS and Windows 9x/ME in the last two decades, and (as stated in dosbox-x.com) two of the main focuses of DOSBox-X are to give the user all the options they need to emulate everything from original IBM PC hardware with 64KB of RAM all the way up to late 90's hardware, and also as a great platform for emulating Windows 3.x, 95, 98 and software written for those versions of Windows, this feature will be extremely helpful for both of these two goals.

**Comment by joncampbell123** [comment]
The latest commit 7c3a01cea8aa10332923698dacef67a16b831e63 has basic functional FAT32 support, including directory enumeration, file open and file create support.

However some IOCTLs are lacking and Windows 98's SCANDISK.EXE will try to fix the filesystem as if FAT16 because of it, so don't run SCANDISK.EXE until that's fixed.

**Comment by Wengier** [comment]
@joncampbell123 Great job! I will be sure to check it out tomorrow.

**Comment by joncampbell123** [comment]
I just implemented INT 21h AX=7302h and now SCANDISK.EXE is happy, except it thinks the free space is being incorrectly reported.

**Comment by joncampbell123** [comment]
FORMAT.COM is now happy in the latest commit when formatting FAT32.

There's probably still some bugs to iron out but it seems stable so far.

**Comment by joncampbell123** [comment]
I got free disk space reporting updated to support FAT32 partitions properly.

The only thing left to figure out is why SCANDISK.EXE always complains about incorrectly reported free space on FAT32 drives.

**Comment by Wengier** [comment]
@joncampbell123 I have tested a 1GB FAT32 image with the latest code. It does indeed work, but I have found following issues in the code (besides the free disk space issue):

1. IMGMOUNT command cannot automatically detect the geometry of the FAT32 image. You have to use some 3rd party tool to find out the values and then manually enter them via the -size option.

2. The built-in DIR command no longer report the free disk space of mounted local drives correctly. The free disk space shown is now completely wrong, e.g. something like "4893,942,319,415,296 Bytes free".

3. The current code (8077632) will NOT compile in VS2015 (at least) unless you change line 265 of drives.h from:
```Bit8u  bootcode[512 - 2/*magic*/ - sizeof(bpb) - 8/*OEM*/ - 3/*JMP*/];```
To:
```Bit8u  bootcode[512 - 2/*magic*/ - sizeof(bpb_union_t) - 8/*OEM*/ - 3/*JMP*/];```
It will compile with GCC though.

**Comment by joncampbell123** [comment]
2 and 3 are fixed.

**Comment by Wengier** [comment]
By the way, the sample FAT32 disk images I used were downloaded from:

https://github.com/procount/fat32images

**Comment by joncampbell123** [comment]
Two things about those images.

First, there's absolutely no boot code in the MBR, just the partition table. If you accidentally boot from this card the CPU's going to run through the zeros and crash when executing the table at the end.

Second, the one and only partition is a FAT32 LBA partition.

So perhaps DOSBox-X could just fake a geometry if it sees a partition of type FAT/FAT32 type LBA or a boot sector full of zeros since in both cases accurate geometry doesn't matter anyway.

**Comment by rderooy** [comment]
I had no problems with mounting a FAT32 image that I created as follows:

IMGMAKE hdd_fat32.img -t hd_2gig
IMGMOUNT C hdd_win98.img
IMGMOUNT D hdd_fat32.img
BOOT C:

Then use win98 conversion software to convert the D: drive to FAT32, and shutdown win98.

Then simply
IMGMOUNT C hdd_fat32.img
worked fine.

**Comment by joncampbell123** [comment]
@Wengier I put some thought into it, and I figured DOSBox-X should make up geometry based on three simple criteria if it can't autodetect. They are:
1. If the raw disk image is 4GB or larger. By the time IDE drives were that large most were already just LBA devices using 16 heads 63 sectors anyway to support C/H/S for backwards compat.
2. If the boot sector is all zeros. If there is no boot code, then there is nothing there that would possibly require the correct geometry (to boot, for example).
3. If the first partition is type "Win95 FAT32 LBA". Normally if Windows 98 has set that partition type it also writes MBR and volume boot code that uses the INT 13h extensions to access using LBA instead of CHS.

**Comment by Wengier** [comment]
@joncampbell123 I agree that making up geometry in such case is probably a good idea, especially for large disk images using LBA.

**Comment by Wengier** [comment]
@rderooy Using a converted FAT32 image seems to be fine, but you can not convert a disk image that is greater than 2GB, so this method's usefulness is limited.

By the way, instead of starting and shutting down Windows 98 to use the conversion software, you can directly start the conversion in the real MS-DOS mode included with Windows 98 too, e.g.

```
IMGMAKE hdd_fat32.img -t hd_2gig
IMGMOUNT C hdd_win98.img
IMGMOUNT D hdd_fat32.img
BOOT C:
CVT D: /CVT32
```

**Comment by Wengier** [comment]
@joncampbell123 I have already fixed the SCANDISK issue that it always complains about incorrectly reported free space on FAT32 drives in my pull request #1558.

**Comment by Wengier** [comment]
I just noticed that the LABEL command does not work on FAT32 drives.

**Comment by joncampbell123** [comment]
Correct, that code is too hard-coded for FAT16/FAT12 root directories to easily port. A FAT32 version needs to follow the root directory allocation chain.

**Comment by Wengier** [comment]
@joncampbell123 The previous AX=7302h code reported that the number of free clusters were unknown, so SCANDISK will try to fix it by writing the correct one. So if AX=7302h returns the actual number of free clusters, then SCANDISK will no longer complain about it.

**Comment by joncampbell123** [comment]
@Wengier That makes sense.

**Comment by joncampbell123** [comment]
@Wengier Are you working on FAT32 LABEL support or should I do it?

**Comment by Wengier** [comment]
@joncampbell123 You can probably fix this one.

**Comment by Wengier** [comment]
@joncampbell123 I was working on serial numbers support etc. Now submitted a new pull request (#1559).

**Comment by joncampbell123** [comment]
FAT32 volume label support finished.

**Comment by Wengier** [comment]
@joncampbell123 Tested and confirmed it works, which is great. I think the only thing left to do is to add FAT32 support for IMGMAKE command. In fact, IMGMAKE command already supports the "hd_4gig" and "hd_8gig" options, but it needs to be updated to use FAT32 instead of FAT16 in such cases. Perhaps you can take a look at it?

**Comment by rderooy** [comment]
@Wengier when you create a hd_4gig or hd_8gig, it does not partition or format it. It is equivalent to -nofs.

```
$ fdisk -l hdd_8gig.img 
Disk hdd_8gig.img: 7.86 GiB, 8414461440 bytes, 16434495 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```
Compared to a fat32 volume:
```
$ fdisk -l hdd_fat32.img 
Disk hdd_fat32.img: 1.99 GiB, 2111864832 bytes, 4124736 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe3657373

Device         Boot Start     End Sectors Size Id Type
hdd_fat32.img1 *       63 4124735 4124673   2G  b W95 FAT32
```
or FAT16
```
$ fdisk -l hdd.img 
Disk hdd.img: 503.52 MiB, 527966208 bytes, 1031184 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe3657373

Device     Boot Start     End Sectors   Size Id Type
hdd.img1   *       63 1031183 1031121 503.5M  6 FAT16
```

**Comment by Wengier** [comment]
@rderooy I have not yet created a hd_4gig or hd_8gig disk image myself because the disk space on my Windows system is about to full. So I will clean up space in order to create such disk images. But the point should be clear: the hd_4gig or hd_8gig options do not support FAT32 yet so it may be updated accordingly as well.

**Comment by joncampbell123** [comment]
I just made one (possibly) final fix to FAT32 support that allows directories to enumerate correctly if the directory cluster chain starts at cluster 65536 or higher. Storing the directory cluster number in the DTA was updated to reflect apparent Windows 98 where the 16-bit cluster field is just extended into the fill[] region by 2 bytes and handled as 32-bit.

Prior to fix, I noticed that sometimes Windows 98 Setup would at random crash because directory enumeration suddenly turned up junk filenames, and after a "successful" Windows 98 install onto a 6GB HDD image, SCANDISK.EXE would report lost clusters. The latest commit fixes that.

**Comment by Wengier** [comment]
@joncampbell123 Great! I also improved the renaming function for FAT drives on my pull request #1563.

**Comment by joncampbell123** [comment]
There's one more issue I'd like to tackle: After running Windows 98 SETUP, SCANDISK complains about "lost clusters" in the root directory. I'll work on that right now.

**Comment by Wengier** [comment]
I found that XCOPY and MOVE commands **do not** work if you try to copy or move file(s) from the root directory of a FAT drive, e.g.

```
C:\TEST>xcopy \SCANDISK.INI
Source path not found - C:\
0 file(s) copied

C:\TEST>move \SCANDISK.EXE .
Source path not found.
```

They will work if you try to emulate the "." entry on the root directory for FAT drives in the code though.

**Comment by joncampbell123** [comment]
I'll check to see if Windows 98 FORMAT adds a '.' entry to the root directory.

**Comment by joncampbell123** [comment]
I am able to run Windows 98 SETUP without issue now, although a 80GB disk image seems to cause Windows 98 SETUP to run out of memory and crash.

**Comment by joncampbell123** [comment]
There are no '.' and '..' entries in the root directory, but I'll look into the issue.

**Comment by Wengier** [comment]
> There are no '.' and '..' entries in the root directory, but I'll look into the issue.

@joncampbell123 That is what I meant by "emulate". Just faking it for debugging purpose and they worked.

**Comment by joncampbell123** [comment]
Apparently for that command, XCOPY uses GetFileAttributes on C:\ which doesn't work. I don't think it's related to '.' and '..'

**Comment by Wengier** [comment]
@joncampbell123 What I meant is that if I faked a "." entry, then functions like GetFileAttributes will work on C:\ just like the other directories. But this is of course only for debugging purpose, not the real solution.

**Comment by joncampbell123** [comment]
Correct. I just verified from a Windows 98 bootable disk image that the FIND FIRST and FIND NEXT INT 21h functions do not return any "." or ".." entries when asked to search C:\*.*

**Comment by joncampbell123** [comment]
Uh, so MOVE/XCOPY try to GetFileAttr "C:\" which DOS_MakeName() converts to an empty string, which the DOS driver doesn't know how to handle and tries to directory match against junk.

**Comment by joncampbell123** [comment]
Latest commit appears to fix the issue. Just return "it's a directory" if asked about the root directory. The latest commit also now explicitly refuses to open/close/create/rename/mkdir/rmdir/setfileattr the root directory in case not doing so would cause any other corruption of the filesystem.

**Comment by Wengier** [comment]
Great! I think the FAT driver is now more stable than ever before.

**Comment by joncampbell123** [comment]
@Wengier I just added support for reading LFNs from a FAT/FAT32 volume. No creating/renaming LFNs yet.

I noticed that the DOS APIs seem to require a LFN for anything to work, which is contrary to Windows 9x where files that fit the 8.3 pattern don't necessarily have a LFN.

For example on a Windows 95 installed image, listing LFNs only for directories with LFNs means that I can browse WINDOWS but "CD WINDOWS" shows nothing in the path and tab completion doesn't work for WINDOWS, but "Program Files" works fine.

**Comment by joncampbell123** [comment]
Hm, Windows 95 too.

**Comment by Wengier** [comment]
@joncampbell123 Thanks for the efforts! On the other hand, I noticed that the newly added lfn config option seems to require a reported DOS version of 7.0. While I think this indeed should be the default setting, it does not need to be a requirement. So I have made a pull request #1566 to make "lfn=auto" the default setting, while allowing "lfn=true" or "lfn=false" to manually override the LFN support.

**Comment by joncampbell123** [comment]
Merged. I think it might be useful if the code in src/dos/dos_files.cpp like DOS_MakeDir() could accept an additional bool that indicates whether the call is from the traditional INT 21h API or the LFN API. I did some tests with the Windows 98 DOS box and the traditional API is not allowed to make long filenames even if the LFN API is enabled. Only the LFN API allows actually using the LFN, otherwise only the SFN is available to traditional INT 21h calls.

Eventually this LFN flag should make it's way down to the local and FAT drive code. I'm going to add code to the FAT driver when I have time to create the LFN entries on mkdir and then remove the LFN entries on rmdir(). The FAT driver needs to know if the call is from LFN to know whether to add LFN entries. rmdir() of course needs to know (if DOS version 7.0 or higher) whether to delete the LFN entries, whether deleting by SFN or LFN.

**Comment by Wengier** [comment]
@joncampbell123 I think you can know this by checking if faux is 256. If it is an LFN call then faux will be the filefind handle with value between 0 and 254.

**Comment by joncampbell123** [comment]
@Wengier That's kind of obscure... What is the purpose of faux exactly?

**Comment by Wengier** [comment]
@joncampbell123 Unlike traditional SFN calls which uses DTA, SFN calls will use filefind handles with value between 0 and 254. So the ways they work are completely different. For SFN calls, the faux value will be fixed to be 256 (because they will use DTA rather than this value, this value is not important), thus it will be pretty easy to differentiate between the two types of calls.

**Comment by joncampbell123** [comment]
@Wengier Can you add comments around the "faux" and related variables to explain that? Without that explanation myself and other developers are going to wonder what those variables are for.

Also to avoid magic constant compares a function that returns a boolean should be added to return whether (faux != 256) aka LFN call is in progress. Something like:

    bool DOS_IsLFNCall(void);

    bool DOS_IsLFNCall(void) {
        return (faux != 256);
    }

**Comment by joncampbell123** [comment]
Long term perhaps "faux" as a variable should be given a more descriptive name like "lfn_filefind_handle" and "256" in that context replaced with LFN_FILEFIND_NONE

**Comment by Wengier** [comment]
@joncampbell123 I think a comment can be like this:

faux (or lfn_filefind_handle) contains the LFN filefind handle that is currently being used, with normal value between 0 and 254 for LFN calls.  The value 255 is used internally by LFN handling functions. For non-LFN calls the value is fixed to be 256.

**Comment by Wengier** [comment]
Also, since this variable only applies to calls that in fact use such a handle, not all functions will use it directly. I used to develop in Windows-only environment by myself, but with current cross-platform environment with more than one developers I agree a change of such usage will be preferred.

**Comment by joncampbell123** [comment]
@Wengier I see faux updated only for LFN find first/find next and in DOS_GetSFNPath. I do not see any code path to set faux for any other LFN call.

Are you sure, for example, that a LFN call to DOS_MakeDir() will see faux != 256?

**Comment by Wengier** [comment]
@joncampbell123 Before making my previous post, I suddenly remembered the scope of this variable did not apply to MakeDir, that is why I said "since this variable only applies to calls that in fact use such a handle, not all functions will use it directly". I did not specifically say "MakeDir" because I am currently preparing to make a pull request to add comment and rename the "faux" variable" so I had not tested myself yet, but I believe you are in fact right.

**Comment by joncampbell123** [comment]
I just pushed some changes that keeps the faux variable but adds the comments and #define constants discussed.

**Comment by joncampbell123** [comment]
@Wengier I already pushed changes adding the comments and the #define for LFN file find handles. The name is still "faux" at this time. Your pull request can change the name to whatever you think is best for that variable.

**Comment by Wengier** [comment]
@joncampbell123 I have already made a pull request (#1567) which changes all "faux" variables to "lfn_filefind_handle". It also changes all relevant 255/256 numbers to LFN_FILEFIND_NONE/LFN_FILEFIND_INTERNAL/LFN_FILEFIND_MAX instead. Furthermore, I added support of "lfn=autostart" which will behave the same as in DOSBox-X 0.83.1 (same as "lfn=auto" except that VER won't change LFN support).

**Comment by Wengier** [comment]
@joncampbell123 I noticed that the current LFN code for FAT drives is still buggy even if I enable read-only mode for the disk image. For example, with MS-DOS 7.x EDIT you cannot open directories with long filenames, and entering "C:" as the directory name will open a file (or subdirectory) in it instead of listing the files in C:.

**Comment by Wengier** [comment]
Commands like ```TYPE "long file name.txt"``` also will not work.

**Comment by Wengier** [comment]
I have fixed the issues that TYPE did not work with long file names and EDIT could not enter directories with long filenames on FAT drives in my pull request #1568. The issue that entering "C:" as the directory name opens a file (or subdirectory) in it instead of listing the files in C: in EDIT is probably related to the root directory handling on FAT drives and is not included in this fix.

**Comment by Wengier** [comment]
The last issue in my previous post has been fixed in my pull request #1569.

**Comment by Wengier** [comment]
I think LFN support for FAT drives in read-only mode is now already in a working state.

**Comment by Wengier** [comment]
@joncampbell123 I have made a pull request #1570 to renamed the force variable (i.e. forcing SFN mode) to a more descriptive name of "force_sfn" and also extended to other SFN calls including UNLINK/MKDIR/RMDIR too in order to make it more complete.

BTW: I greatly appreciate your knowledge about FAT file systems and your efforts to support it.

**Comment by Wengier** [comment]
@joncampbell123 I noticed that "MD Program Files" on FAT drives will create a SFN name like "PROGRAMF.ILE" (the LFN name is correct though). Perhaps it should be something like "PROGRA~1" instead?

**Comment by joncampbell123** [comment]
Certainly. As more functions support LFN generation the code will need to generate a SFN of that kind to avoid conflicts.

**Comment by joncampbell123** [comment]
I have some practice with FAT filesystem structures. The format generator is good enough to make any size FAT32 partition that Windows XP through Windows 10 are happy with.

https://github.com/joncampbell123/datamtoolbox2/tree/master/datamtoolbox-v2/libmsfat

**Comment by joncampbell123** [comment]
Collecting documentation over time helps as well:

http://hackipedia.org/browse.cgi/Disk%20formats/Filesystems/FAT%2c%20File%20Allocation%20Table%20%28DOS%2c%20Windows%29

**Comment by Wengier** [comment]
@joncampbell123 I am currently writing the Generate_SFN function, should be submitted in a while.

**Comment by Wengier** [comment]
I have already submitted my pull request #1571 for 8.3 file name generation.

**Comment by joncampbell123** [comment]
Awesome, been working on rmdir, file create, and rename LFN support.

**Comment by Wengier** [comment]
@joncampbell123 Good job! I noticed that you can rmdir by SFN, but you cannot rmdir by LFN though. I think it should try to match both.

**Comment by joncampbell123** [comment]
I am working on that right now. There's some cleanup that can be done to the FAT driver, especially where the code can just look up the directory/file once instead of twice (first for the dirent, then the parent dir).

**Comment by joncampbell123** [comment]
One DOS API bug I noticed is that attempting to delete a directory (instead of via the RMDIR call) does not return an error, but does not do anything.

This isn't the FAT driver's doing, because in that case the call doesn't even make it to the FAT driver.

**Comment by joncampbell123** [comment]
@Wengier The latest code is able to rmdir by SFN and LFN, and will reject attempts to rmdir a file. Mkdir will create a directory and will reject if it already exists. Still working on the FAT driver.

**Comment by joncampbell123** [comment]
@Wengier Here's what I mean:

    *works*

    echo >abc
    del abc

    *should throw an error*

    mkdir abc
    del abc

**Comment by Wengier** [comment]
@joncampbell123 I can see what you meant, and thanks for the fix. I will be sure to test tomorrow.

**Comment by joncampbell123** [comment]
@Wengier I just finished the DOS FAT driver Rename() cleanup.

Two issues I've noticed is that the DOS API is unable to provide renaming of a directory once the name is longer than 8.3. It's not LFN-related, because a 8.3 filename with an LFN to allow lowercase works fine. It's not the FAT driver, because as far as I can tell the FAT driver's Rename() method isn't even called in that case.

Second issue is that the REN/RENAME command built into the DOS shell seems to have problems parsing quoted long filenames, which makes it harder to test LFN renaming.

**Comment by Wengier** [comment]
@joncampbell123 I have fixed built-in REN/RENAME command's handling of quoted long filenames. The LFN handling was missing before calling FindFirst/FindNext. However, I don't think the built-in DEL command has this problem because the LFNs would be converted to SFNs before calling them. Could you give some specific example that DEL command does not work with quoted LFNs? Thanks?

As for the issue of renaming directories, I checked the reason is that DOS_Rename will call GetFileAttr on the FAT driver to confirm the directory actually exists, but FAT driver's GetFileAttr function cannot handle LFNs properly ahis timt te. So I think the GetFileAttr/SetFileAttr functions in drive_fat.cpp need to be updated to support LFN too.

**Comment by Wengier** [comment]
@joncampbell123 As for the issue that “attempting to delete a directory (instead of via the RMDIR call) does not return an error, but does not do anything". This is NOT a DOS API bug, but a bug of the built-in DEL command. DOSBox-X's DEL command's function has been incomplete for a long time, and I already made significant improvements to it in DOSBox-X 0.83.1, but I am aware that its function is still incomplete for now.

**Comment by joncampbell123** [comment]
@Wengier I fixed the DEL command to print an error message if you attempt to delete a directory.

**Comment by joncampbell123** [comment]
@Wengier DEL seems to fail on files that are 8.3 or shorter that have a space in them.

For example:

    echo >"abc def"
    del "abc def"

**Comment by joncampbell123** [comment]
@Wengier Question: Why do the LFN APIs accept the string from the guest and add quotation marks around the string?

It would probably simplify the code and eliminate bugs if the string from the guest were taken as-is and the rest of the code were to know whether the name came from the LFN or SFN interface.

https://github.com/joncampbell123/dosbox-x/blob/master/src/dos/dos.cpp#L3098

**Comment by Wengier** [comment]
@joncampbell123 I am currently improving the builtin DEL command so that it will work in a way more similar to real DOS, e.g. "DEL directory" will confirm if it will delete all files in the specified directory. Also it will take care of the failure on files that are 8.3 or shorter that have a space in them.

As for the quotes for LFN API, I think that code already worked pretty well as is (in DOSBox-X and vDosPlus etc). It is possible to make changes, but will affect a lot of other places too.

**Comment by joncampbell123** [comment]
@Wengier I see. The LFN code works fine as it is, so far, but long term should be cleaned up not to require quoting and unquoting the string like that for LFN handling.

**Comment by Wengier** [comment]
@joncampbell123 I have already made my pull request #1575 for improvements to DEL command etc.

**Comment by joncampbell123** [comment]
That works. I also noticed the addition of COMMAND.COM-like behavior where if DEL detects the name is a directory it offers to delete everything in the directory. :+1:

**Comment by Wengier** [comment]
@joncampbell123 I think the GetFileAttr/SetFileAttr functions still need to support LFNs so that commands like REN will work with directories with long names.

**Comment by joncampbell123** [comment]
@Wengier I agree. However it already seems to work fine at least in DOSBox-X's shell.
![command_000](https://user-images.githubusercontent.com/6245486/82490972-e1aae000-9a98-11ea-887b-7b490bdb94c2.png)

**Comment by joncampbell123** [comment]
Also works from Windows 95's COMMAND.COM and ATTRIB.EXE commands.
![command_001](https://user-images.githubusercontent.com/6245486/82491052-fbe4be00-9a98-11ea-8548-4cb08be00df0.png)

**Comment by Wengier** [comment]
@joncampbell123 I did not test the Win95 ATTRIB.EXE for this yet, but the built-in ATTRIB currently works with long names because it will automaticlaly convert the names to SFNs first using other functions, and then call GetFileAttr with shortnames. I know this because I implemented the ATTRIB command. If it directly calls GetFileAttr with LFNs, I believe it will probably fail too.

**Comment by Wengier** [comment]
I will submit a pull request to fix this.

**Comment by Wengier** [comment]
@joncampbell123 With the changes in pull request #1577, I think the LFN feature for FAT drives is now more or less complete. Thanks a lot for your effort to support this feature.

**Comment by Wengier** [comment]
> @Wengier I see. The LFN code works fine as it is, so far, but long term should be cleaned up not to require quoting and unquoting the string like that for LFN handling.

I have remembered that I introduced quoting a few years ago to guarantee the integrity of the string. Quoting a string is never required, but if it is not quoted, functions like DOS_MakeName may chop space and some other special characters in the string. Quoting a string will prevent this from happening. Even though spaces and some other special characters may be allowed in 8.3 names in certain cases, many/most DOS functions or programs will not actually accept them, thus quite problematic. So I think the default DOS_MakeName behavior can indeed prevent such problems in most cases.
