### ISSUE TITLE
Reloading a save state after closing DOSBox-X

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1576]
**Describe the bug**
DOSBox-X allows to reload a save state after reopening the emulator without reloading the executable of the game: the screen fills with blinking ASCII characters and the emulator must be restarted.

**To Reproduce**
1. Launch a game
2. Save the state with F11+F1
3. Close DOSBox-X
4. Reopen DOSBox-X
5. At DOS prompt press F11+F2

**Expected behavior**
This not official patched DOSBox version (https://www.vogons.org/viewtopic.php?f=41&t=53116) check if the executable is running before loading the save state: if not, in the Status Windows appears the message "Aborted. Check your program name: EXECUTABLE_NAME"

**Screenshots**
![command_000](https://user-images.githubusercontent.com/58113425/82499745-83aae680-9af2-11ea-85dc-f6c23b08e9b6.png)

**Environment (please complete the following information):**
 - Windows 10 64 bit
 - DOSBox-X 0.83.1 x64 SDL2 (dosbox-x-windows-20200502-170825-windows.zip)
 - Default configuration

**Comment by Wengier** [comment]
The save state feature is **never** included in the official DOSBox SVN builds. It is a patch developed by another programmer. DOSBox-X used an earlier version of the patch, which is not yet in a mature state.

**Comment by MX9000** [comment]
Thanks Wengier,
I corrected my bug report by specifying that it is an unofficial version of DOSBox.
I know that the save state function in DOSBox-X is not yet stable but I was curious to try it!

**Comment by joncampbell123** [comment]
It's not very much developed and does not save all state yet.

**Comment by Wengier** [comment]
@MX9000 I have already ported the improved save state feature to DOSBox-X. It is still not perfect, but it should certainly work better than the previous save state feature.

**Comment by MX9000** [comment]
Thanks so much Wengier!
I'll wait for the next build and will definitely try it.

**Comment by MX9000** [comment]
I have just tested the new version (dosbox-x-windows-20200630-163819-windows.zip) and I have seen that now DOSBox-X shows a program mismatch warning box if the executable is not running in the emulator.
Thanks again!
