### ISSUE TITLE
SDL2 build failure

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1624]
**Describe the bug**
On Fedora 32 running ./build-sdl2 fails since the SDLNet change.
```
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPClientSocket::TCPClientSocket(int)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:57: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPClientSocket::TCPClientSocket(_TCPsocket*)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:114: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPClientSocket::TCPClientSocket(char const*, unsigned short)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:139: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPServerSocket::TCPServerSocket(unsigned short)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:298: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o): in function `MidiHandler_timidity::timidity_write_data(void const*, int)':
/home/robert/github/dosbox-x/src/gui/midi_timidity.h:326: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o):/home/robert/github/dosbox-x/src/gui/midi_timidity.h:326: more undefined references to `SDLNet_GetError' follow
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:470: dosbox-x] Error 1
make[3]: Leaving directory '/home/robert/github/dosbox-x/src'
make[2]: *** [Makefile:530: all-recursive] Error 1
make[2]: Leaving directory '/home/robert/github/dosbox-x/src'
make[1]: *** [Makefile:390: all-recursive] Error 1
make[1]: Leaving directory '/home/robert/github/dosbox-x'
make: *** [Makefile:327: all] Error 2
```

**Comment by joncampbell123** [comment]
is C_SDL_NET defined in config.h?

**Comment by rderooy** [comment]
```
$ fgrep C_SDL_NET config.h
#define C_SDL_NET 1
```

**Comment by joncampbell123** [comment]
Which build script are you using?

There is no build-sdl2 script.

**Comment by rderooy** [comment]
Sorry, I forgot. It is a copy of build-debug-sdl2 with --enable-debug=heavy changed to --disable-debug

But running build-debug-sdl2 fails the same way

**Comment by joncampbell123** [comment]
Hold on, SDLnet on Centos 8 is failing for SDL2 builds because it checks for SDL1 *sigh* This is why Linux builds disabled SDLnet with SDL2 in the first place.

Funny enough, VS2019 has no problems compiling SDL2 with SDLnet.

**Comment by rderooy** [comment]
You should probably get some rest, and think about it in the morning :-)

**Comment by joncampbell123** [comment]
@rderooy Thanks :) but I think I fixed it, along with a few other annoyances.

**Comment by rderooy** [comment]
@joncampbell123 

I just pulled the latest changes, and SDL2 build still fails as it did before.
```
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPClientSocket::TCPClientSocket(int)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:57: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPClientSocket::TCPClientSocket(_TCPsocket*)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:114: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPClientSocket::TCPClientSocket(char const*, unsigned short)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:139: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `TCPServerSocket::TCPServerSocket(unsigned short)':
/home/robert/github/dosbox-x/src/hardware/serialport/misc_util.cpp:298: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o): in function `MidiHandler_timidity::timidity_write_data(void const*, int)':
/home/robert/github/dosbox-x/src/gui/midi_timidity.h:326: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o):/home/robert/github/dosbox-x/src/gui/midi_timidity.h:326: more undefined references to `SDLNet_GetError' follow
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:470: dosbox-x] Error 1
make[3]: Leaving directory '/home/robert/github/dosbox-x/src'
make[2]: *** [Makefile:530: all-recursive] Error 1
make[2]: Leaving directory '/home/robert/github/dosbox-x/src'
make[1]: *** [Makefile:390: all-recursive] Error 1
make[1]: Leaving directory '/home/robert/github/dosbox-x'
make: *** [Makefile:327: all] Error 2
```

And just to be sure it was nothing with my local copy, I deleted it, and re-cloned it. But it fails the same way.

**Comment by CarolinaJones** [comment]
Howdy Folks,

I'm having the exact same errors on a Raspberry Pi 3B, under Buster. Same circumstances as _**rderoy**_. I have overcome the errors by manually editing out references to SDLNet_GetError but obviously this isn't a "proper" solution!

./configure --enable-sdl2 --disable-x11 --enable-core-inline --enable-optimize --enable-mt32 --disable-debug
make -j$(nproc) && sudo make install

Many thanks! :)

**Comment by CarolinaJones** [comment]
@joncampbell123 

I just pulled the latest again and this is the result. I guess I could have created a new issue but this seems to be related to the issue experienced by, @rderooy 

Thanks for your wonderful work! :)

g++  -g -std=gnu++11  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -I/home/pi/code/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/pi/code/dosbox-x/vs2015/sdlnet/linux-host/include/SDL   -L/home/pi/code/dosbox-x/vs2015/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a aviwriter/libaviwriter.a  xBRZ/libxbrz.a  -lasound -lm -ldl -lpthread -L/usr/local/lib -Wl,-rpath,/usr/local/lib -Wl,--enable-new-dtags -lSDL2 -ltinfo -lfreetype -lSDL_net -lz -lpng -lz -lpcap -lfluidsynth -lavcodec -lavformat -lavutil -lswscale -lavcodec -lGL
/usr/bin/ld: gui/libgui.a(midi.o): in function `MidiHandler_timidity::connect_to_server(char const*, int, _TCPsocket**)':
/home/pi/code/dosbox-x/src/gui/midi_timidity.h:219: undefined reference to `SDLNet_GetError'
/usr/bin/ld: /home/pi/code/dosbox-x/src/gui/midi_timidity.h:225: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o): in function `MidiHandler_timidity::timidity_write_data(void const*, int)':
/home/pi/code/dosbox-x/src/gui/midi_timidity.h:326: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o): in function `MidiHandler_timidity::timidity_ctl_command(char*, char const*, ...)':
/home/pi/code/dosbox-x/src/gui/midi_timidity.h:252: undefined reference to `SDLNet_GetError'
/usr/bin/ld: gui/libgui.a(midi.o): in function `MidiHandler_timidity::MidiHandler_timidity()':
/home/pi/code/dosbox-x/src/gui/midi_timidity.h:45: undefined reference to `SDLNet_GetError'
/usr/bin/ld: hardware/libhardware.a(ipx.o):/home/pi/code/dosbox-x/src/hardware/ipx.cpp:1104: more undefined references to `SDLNet_GetError' follow
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:471: dosbox-x] Error 1
make[3]: Leaving directory '/home/pi/code/dosbox-x/src'
make[2]: *** [Makefile:531: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/code/dosbox-x/src'
make[1]: *** [Makefile:391: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/code/dosbox-x'
make: *** [Makefile:328: all] Error 2

Thank-you, thank-you, thank-you! :)
Caroline

**Comment by joncampbell123** [comment]
This might be related to recent changes to enable SDLnet for SDL2 builds. Updates were done to enable on Linux and Windows, but I haven't changed the Mac OS X builds yet.

**Comment by CarolinaJones** [comment]
Thanks,
This issue is actually on my Raspberry Pi, running Buster .. :)

**Comment by rderooy** [comment]
Alo want to re-confirm from my side that the SDL2 build **on Linux** is still broken.

**Comment by rderooy** [comment]
I confirm that I can build the SDL2 version on Linux again with this change.

**Comment by CarolinaJones** [comment]
Confirmed for me too, on the Raspberry Pi .. Thanks! :)
