### ISSUE TITLE
Win9x broken with recent change

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1904]
**Describe the bug**
Due to a recent change I can no longer start Windows 95 or 98.

I get to see the windows splash screen and it immediately crashes with:
```
LOG: Limit check 110000+4-1 = 110003 > ffff
LOG: Segment limit violation
LOG: E_Exit: Illegal descriptor type 4 for int D
E_Exit: Illegal descriptor type 4 for int D
```
This happens with both the SDL1 and SDL2 binaries on Linux and happens with both ``output=surface`` and ``output=opengl``. As this regards Win9x, I'm obviously running with ``core=normal``.

I tried both todays latest git HEAD and the 0.83.6 release version and both are broken.
This has nothing to do with selinux in this case.

**Comment by Allofich** [comment]
One of the recent SVN commits I merged involves CPU code.

https://github.com/joncampbell123/dosbox-x/commit/14f3f5f169c4dc67cfd4a24a9dc381fdbcc718f5

It's just 2 added lines so it would be easy to try reversing this change.

**Comment by rderooy** [comment]
That was committed 22 days ago, I think that would have been noticed by now. And in any case, to verify I removed the lines and it still crashes the same way.

**Comment by rderooy** [comment]
I will start with a git bisect to locate the offending commit.

**Comment by Allofich** [comment]
OK, thanks for checking anyway. That was the only potential commit that came to mind among the ones I have sent in recently.

**Comment by rderooy** [comment]
I ended up with the following commit. I will try to do some testing by reverting it.

61d2e1e9493ad6c23521f7db744639604d7e89c1 is the first bad commit
commit 61d2e1e9493ad6c23521f7db744639604d7e89c1
Author: Jonathan Campbell <jonathan@castus.tv>
Date:   Wed Sep 30 00:05:57 2020 -0700

    Fix FFMPEG libavcodec detection, use pkg-config

 configure.ac | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)

**Comment by rderooy** [comment]
Indeed, if I revert https://github.com/joncampbell123/dosbox-x/commit/61d2e1e9493ad6c23521f7db744639604d7e89c1 it works again.

Here is what the old check returns:

```
checking for avcodec_open2 in -lavcodec... yes
checking libavcodec/avcodec.h usability... no
checking libavcodec/avcodec.h presence... no
checking for libavcodec/avcodec.h... no
```

Compared to the new check:
```
pkg-config --exists libavcodec; echo $?
0
```

```
$ rpm -qa|grep ffmpeg
ffmpeg-devel-4.3.1-9.fc33.x86_64
ffmpeg-libs-4.3.1-9.fc33.x86_64
ffmpeg-4.3.1-9.fc33.x86_64
```

**Comment by joncampbell123** [comment]
Wait, what?

That commit changes only configure.ac and whether or not FFMPEG's avcodec libraries are involved.

How the heck does that affect Win 9x?

Seems like a coincidence.

**Comment by rderooy** [comment]
Before ffmpeg was not getting included despite the fact that I have the library and header files installed. With the new check it is getting included.

**Comment by dreamer** [comment]
Cmake or autotools? We had similar problems with other libraries (we use autotools only for now).

**Comment by rderooy** [comment]
autotools

Using for instance the build-debug-sdl2 script.

**Comment by joncampbell123** [comment]
@rderooy Right, same problem here. MPEG-TS capture mode was not available until I made that fix despite having FFMPEG installed. libavcodec was unusable in the test because it relied on functions in libavutil.

**Comment by joncampbell123** [comment]
Not sure where to put this, but a friend sent me this link about possible spamming of open source issue trackers on GitHub for a free T-shirt.

https://blog.domenic.me/hacktoberfest/

**Comment by inukaze** [comment]
Just today i try to install Win95 RTM, Win 95 OSR 2.5, Win98FE, Win98SE and none pass the part after reboot the system, just appears the Startup Image, twice, and after i just got a Black Screen.

i had think to make a New Issue with that and for ask if johncampbell123 & dsn900 can test with the spanish versions of that OS. well i am going to trying with dosbox-x-v0.83.2 (sdl1) and with the follow configuration :

vmemsize=8
memsize=512
core=dynamic
cputype=pentium_mmx
cycles=97240

**Comment by rderooy** [comment]
If you want to use Win9x and you run into boot problems, please try the
0.83.5 release version.
And also be sure to follow the Win9x guide on the wiki.

**Comment by joncampbell123** [comment]
@inukaze Do not use dynamic core with Windows 95/98/ME. Use normal core. Windows 95's page fault handling and preemptive multitasking is not compatible with dynamic core.

**Comment by inukaze** [comment]
joncampbell123 : Thanks well i go to try again because after finish the installation i got "Insufficiente Memory" xD

Ok then i try with the follow configuration instead : 

```
vmemsize=8
memsize=512
core=normal
cputype=pentium_mmx
cycles=97240
enable msr= false
voodoo=opengl
```

**Comment by rderooy** [comment]
Please follow the wiki, as mentioned there 512MB is too much.

**Comment by Wengier** [comment]
@inukaze  The Wiki guides for installing and running Windows 95 and 98 are here:

https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-95

https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-98

**Comment by inukaze** [comment]
@Wengier : Thank you very much, i first try with the old methods i use with
dosbox daum
jdosbox
dosbox-ece

Well after the change i say, i install Windows95 OSR 2.5 Spanish version without problems. Well i am goint to try if i can share files on intranet using samba protocol or something.

Dunno why the Windows95 is running i can't change for example the "D" drive choosing a different ISO or Directory ? 

Yesterday startup the dosbox-x native (0.83.2-SDL1 becuase is the latest i can compile under Slackware 14.2) and well i use "[CTMouse](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/ctmouse.html)" & "[Dos Navigator](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/1.2/pkg-html/dn2.html)" from "FreeDOS" to have a easy way of file management between the hdd image i use for win95
and the mounted directory like cdrom to copy all content to the hdd, and when i finish i boot the hdd image to install the things i had on directory or iso.

Well i don't know why tools like that are not part of dosbox-x i suppose can be a legal reasons with licenses or something. that thing happend me too with DOSBox-X-MinGW-SDL1 64 Bits for Windows via Wine 5.17

The another dunno i had is if @Wengier and/or @joncampbell123 had try to use softwares like (i download from FreeDOS) :
 
["CTMouse"](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/ctmouse.html) for enable mouse support under d.o.s mode (well i don't know if actually include something like this)

["Dn2"](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/1.2/pkg-html/dn2.html) for have something similar to Midnight Commander or Norton Commander. I had try to "[DOSZip Commander](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/doszip.html)" but for example when i try to delete folders with a lot sub-folders and files, this tools just stuck or hang dosbox-x.

[FreeDOS Desktops](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/group-gui.html) : [Seal](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/seal.html), [oZone GUI](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/ozonegui.html) or [OpenGEM](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/opengem.html)

and the last software is very useful for me is [GRLDos](http://www.gr-lida.org/grldos/) with this, i had months searching all games of dosbox i can distribute legally with this software for share a collection using dosbox-x without legal problems, well i had make a list but i ever check again when i think on put a particular game in the package i am making xD to notice if the licence still allow free distribution.

**Comment by Wengier** [comment]
@inukaze Both CTMOUSE and DN2 are open-source software, so there is certainly no legal issue for including them. However, the reason for not including CTMOUSE is that it is largely unnecessary for the built-in DOS shell. It is useful for guest DOS systems, but they cannot see the Z drive anyway. As for DN2, there are a lot of files in it, in addition to the main executable. Perhaps it can be mounted to a different drive automatically, if you choose to include it during the DOSBox-X installation.

**Comment by inukaze** [comment]
@Wengier : Thanks for the answer. well i know the zip of dn2 came with various files but the most esential you need to run it are 
DN.COM, DN.PRG, ENGLISH.DLG, ENGLISH.LNG

Well i prefer the colors of "norton" (COLORS\NORTON.PAL) inside the zip because when you use just this files, the default pallete loaded is Jaroslaw (i don't know why) and is awful for me. 
![DN2Min001](https://user-images.githubusercontent.com/1647332/95169216-88f68e00-0780-11eb-9570-4ed58bc1230c.png)

i prefer Norton, i rename just the files i want of palletes for example "DEFAULT.PAL" to "DN2DFALT.PAL", NORTON.PAL TO "DN2ORTON.PAL" and "VAX.PAL" to "DN2VAX.PAL" when you run the first time some files and folders are generated like : 
[Files] -> DN.INI, DN.HIS, DN.FLG, DN.CFG, DNHGL.GRP, DNINI.IN_
[Folders] -> TEMP, TEM

![DN2Min002](https://user-images.githubusercontent.com/1647332/95169259-97dd4080-0780-11eb-92ac-b4cb4b9c2e80.png)

i love when DOSBox-X deciede include The [Edit](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/edit.html) just requiere "Edit.exe" & "Edit.hlp" to work fine i love this text editor because allow open multiples files in "Windows" for example this screenshot 
![FreeDOSEdit](https://user-images.githubusercontent.com/1647332/95168077-bc381d80-077e-11eb-8153-8fe27d0ea0a4.png)

I am testing Seal 2 when i got various errors when usen it but can be util in some situations xD. well i think this kind of programs like seal2 dont be included. but something like dn2 yes just for be an excelent file manager.
![Seal2](https://user-images.githubusercontent.com/1647332/95171362-ca3c6d00-0783-11eb-874b-3398bbe727ea.png)

**Comment by rderooy** [comment]
@inukaze Could you please open a separate issue. This has nothing to do with what this issue was opened about.

This issue was about dosbox-x crashing when booting Win9x.

**Comment by rderooy** [comment]
I am not able to trigger this any longer. Not sure what changed, but since this thread has gone way off topic I will close it.
