### ISSUE TITLE
Ctrl+C makes a heart symbol

### ISSUE THREAD

**Issue by JGCYASYS** [joncampbell123/dosbox-x#2168]
I'm using the latest release of dosbox-x. The program I'm using is the GNU ed port to DOS via DJGPP and there is a problem with sending a break signal with Ctrl+C. It makes a heart symbol instead and I can't figure out a way to be able to exit editing mode in GNU ed for DOS. Can I have some help please.

**Comment by joncampbell123** [comment]
Does CTRL+C work with anything else?

Perhaps DOSBox-X is unable to send a CTRL+C signal to protected mode applications.

**Comment by JGCYASYS** [comment]
> 
> 
> Does CTRL+C work with anything else?
> 
> Perhaps DOSBox-X is unable to send a CTRL+C signal to protected mode applications.
I tested it in EDIT and outside of programs at the command line. Nothing happened in EDIT and command line gave me a ^C. You can test out the program yourself because I got it from here:
ftp://ftp.delorie.com/pub/djgpp/current/v2gnu/ed-1142b.zip
Also the source code if you need it:
ftp://ftp.delorie.com/pub/djgpp/current/v2gnu/ed-1142s.zip

**Comment by grapeli** [comment]
@JGCYASYS 
ed.info
_"An interrupt (typically <Control-C>) has the effect of **aborting the current command** and returning the editor to command mode"._
You leave ed-a by command:
q

or Ctrl-D (sends an EOF to close the terminal). Doesn't work under dos.

**Comment by JGCYASYS** [comment]
> 
> 
> @JGCYASYS
> ed.info
> _"An interrupt (typically ) has the effect of **aborting the current command** and returning the editor to command mode"._
> You leave `ed` by command:
> q
> 
> or Ctrl-D (sends an EOF to close the terminal). Doesn't work under dos.

I'm testing GNU ed for DOS right now in a VM for freedos 13 livecd. It works as intended like on linux. I can type "." during edit mode to return to command mode and typing Ctrl+C and then enter or Ctrl+D and enter will return to me command mode. In Dosbox-X I'm stuck in edit mode if I type . or Ctrl+C or Ctrl+D. I'm convinced now this is a bug because it works just like linux under freedos but not dosbox-x.

**Comment by grapeli** [comment]
@JGCYASYS 
`ed` does not work properly under dosbox-x.
Neither command is functioning.
`a` [append]
`s` [substitute]
`w` [write]
`q` [quit]

`ctrl-d` has no function in `ed` under freedos. Also under dosemu2.

**Comment by ThePillenwerfer** [comment]
Ctrl-z is a bit iffy too.  If you try `copy con test`, enter some text and then press Ctrl-z to insert and End of File marker it puts → on screen rather than ^Z.  It does however work properly.

![Screenshot at 2021-01-08 01-11-08](https://user-images.githubusercontent.com/42588539/103962282-87a57a80-514e-11eb-952b-79d552cb6126.png)

**Comment by Wengier** [comment]
@JGCYASYS The issue that Ctrl+C makes a heart symbol in GNU ed is hopefully fixed in #2171.

@ThePillenwerfer You can consider that pressing Ctrl-Z shows → rather than ^Z to be a cosmetic issue. It will eventually be fixed in general (because it does not limit to Ctrl-Z I believe).

**Comment by grapeli** [comment]
@Wengier 
It only changed that you can abort malfunctioning `ed` under DOSBox-X without needing to restart DOS.
`ed` still doesn't work properly under dosbox-x compared to how the same version behaves under FreeDOS.

`Ctrl-C` does not terminate `ed` under Linux or FreeDOS.

`ed` is the progenitor of programs such as sed, vi. If you know how to handle them, you can handle ed.

**Comment by JGCYASYS** [comment]
> 
> 
> @JGCYASYS The issue that Ctrl+C makes a heart symbol in GNU ed is hopefully fixed in #2171.
> 
> @ThePillenwerfer You can consider that pressing Ctrl-Z shows → rather than ^Z to be a cosmetic issue. It will eventually be fixed in general (because it does not limit to Ctrl-Z I believe).

It's not just Ctrl+C that doesn't work which hopefully gets fixed in the upcoming merge. I mentioned above that using . to quit GNU ed under dosbox-x doesn't quit editing mode to return to command mode like how it does under linux or freedos. That too needs to be fixed among a few other things.

**Comment by Wengier** [comment]
@grapeli and @JGCYASYS Yes, I believe the DOS read device function is not implemented correctly. As a result, commands like q have no effect as this time.

**Comment by JGCYASYS** [comment]
Thanks for the recent update. CTRL+C works in ed now along with CTRL+Z. However, using "." to exit edit mode still doesn't work and that needs to be fixed as well.
