### ISSUE TITLE
Launchbox and Dosbox-X Mount´s from Launchbox not working

### ISSUE THREAD

**Issue by Starfoxfs** [joncampbell123/dosbox-x#2439]
Hi,

i use Launchbox 11.10 with Dosbox-X 0.83.12 SDL2.

In Launchbox no Mounts and Imgmounts working because Dosbox-X don´t accept the Command from Launchbox for mounting these.

I think because there are some backsticks `` in the mount & imgmount Commands from Launchbox ?!?

`IMGMOUNT E 'D:\Test.cue'` didn´t work but required for Launchbox
`IMGMOUNT E "D:\Test.cue"` works
`IMGMOUNT E D:\Test.cue` also works 

`MOUNT` same as IMGMOUNT

In Dosbox SVN and normal Dosbox 0.74 it works without Problems

**Comment by Wengier** [comment]
Thanks for reporting this. I believe this issue is similar to Issue #1535, except that Issue #1535 was about the MOUNT command, and this one is about the IMGMOUNT command. In such case the single quotes (') are used (not the backsticks [`]). This issue can be worked around for the Windows platform similar to that issue. Please check out the updated DOSBox-X SDL2 binary:

* [dosbox-x-mingw64-sdl2.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip)

**Comment by Starfoxfs** [comment]
Good Morning,

thanks for the Mingw Build the Mounts working now, but my Keyboard in Games not. 

In Dosbox Command prompt Keyboard works normaly but not in Games.

**Comment by Starfoxfs** [comment]
Ok i tested a little bit.

With your attached Mingw Version:
- Mounting works from Launchbox (but not if spaces in original Path)

- What not works is dgVoodoo2 with glide=true if the glide2x.dll is in Dosbox Folder
- Another issue with your attached Version is, started from Launchbox 11.10 the Keyboard doesn´t work properly.

So i downloaded the MingW x64 SDL2 0.83.13 from Dosbox-X Site: [https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.12/dosbox-x-mingw-win64-20210401030652.zip](url)

Here i have this issues:
- Keyboard also doesn´t work properly started from Launchbox 11.10
- dgVoodoo2 works !
- Mounting doesn´t work started from Launchbox 11.10

**Comment by Starfoxfs** [comment]
Update:

I used the reference.conf File and now Keyboard and dgVoodoo2 works fine (launched from Launchbox)

The only thing remains is the Spaces in the original Path if mounting like ...\Descent 2\.... not works but ...\Descent-2\... works

This mounting with backsticks ´ only works in MingW SDL2 Builds ?

**Comment by Wengier** [comment]
For mounting paths with spaces please enclose the paths with double quotes ("), e.g. "...\Descent 2....". Support for single quotes in the paths is a workaround for Windows systems only, and other builds will also work with a new release version.

**Comment by Starfoxfs** [comment]
Good Morning Wengier,

in Launchbox i don´t have the choice to set double quotes (") to the Mounting Path Launchbox sets backsticks (`) 

Or i have to rename 350 Dos-Game Pathes in Windows and Launchbox.

**Comment by Wengier** [comment]
@Starfoxfs It is not backsticks (`) but single quotes ('), but in any case I wonder if there are many paths among your DOS games have spaces?

**Comment by Starfoxfs** [comment]
yeah i have named many games like this "Descent 2" "Descent 1 Anniversary" "Extreme Assault" "Simon the Sorcerer" ....

It's a habit of Windows times 

Before i used Dosbox SVN Daum and this works with double quotes together with Launchbox.

But i wan´t to use your Versions because SVN is outdated and with dgVoodoo2 3dfx has better Performance as in Dosbox Daum.

**Comment by Wengier** [comment]
@Starfoxfs Try the following updated DOSBox-X SDL2 binary and mount your CD images in paths with spaces using IMGMOUNT command:

* [dosbox-x-mingw64-sdl2.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip)

**Comment by Wengier** [comment]
@Starfoxfs Try the following updated DOSBox-X SDL2 binary and mount your CD images in paths with spaces using IMGMOUNT command:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Starfoxfs** [comment]
With the sdl2 update it work´s with (") and IMGMOUNT

but only with (")

**Comment by Wengier** [comment]
@Starfoxfs If a command does not work as expected, can you list the exact command being used? Thanks.

**Comment by Starfoxfs** [comment]
Yes

This Works now:
`IMGMOUNT E "D:\Emulatoren-Spielearchiv\CD-Rom-Games-Archiv\MS-DOS\Descent 2\Descent2+VertigoAudio.cue" -t iso -fs iso`

This doesn´t work:
`IMGMOUNT E ´D:\Emulatoren-Spielearchiv\CD-Rom-Games-Archiv\MS-DOS\Descent 2\Descent2+VertigoAudio.cue´ -t iso -fs iso`

or:
`IMGMOUNT E D:\Emulatoren-Spielearchiv\CD-Rom-Games-Archiv\MS-DOS\Descent 2\Descent2+VertigoAudio.cue -t iso -fs iso`

**Comment by Wengier** [comment]
@Starfoxfs You don't need `` -t iso -fs iso`` in such cases. Try this:

IMGMOUNT E 'D:\Emulatoren-Spielearchiv\CD-Rom-Games-Archiv\MS-DOS\Descent 2\Descent2+VertigoAudio.cue'

**Comment by Starfoxfs** [comment]
I don´t need this but Launchbox does this automaticly

**Comment by Starfoxfs** [comment]
![command_000](https://user-images.githubusercontent.com/62878094/114542635-af254b00-9c47-11eb-916d-2210d6c885b0.png)

**Comment by Wengier** [comment]
@Starfoxfs Try this updated DOSBox-X build then:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Starfoxfs** [comment]
This works 👍

**Comment by Wengier** [comment]
@Starfoxfs Glad to hear that. The build I just uploaded is a 32-bit VS SDL2 build.

**Comment by Starfoxfs** [comment]
Thanks 👍 

Will this be implentened in next official Builds then ?

**Comment by Wengier** [comment]
@Starfoxfs The current workaround will hopefully be implemented in the next official builds. But for any remaining issue(s) for mounting paths with spaces in LaunchBox I would strongly recommend you to use the associated DOS SFN names instead. As you may already know, each Windows paths with spaces have an associated DOS LFN name, e.g. `C:\PROGRA~1` for `C:\Program Files`, so you just use the DOS LFN names in LaunchBox in such case and it will hopefully work.

**Comment by Wengier** [comment]
@Starfoxfs In any case, you can try the updated DOSBox-X build for mounting paths with spaces using `MOUNT` command as well in LaunchBox:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Starfoxfs** [comment]
Goog Morning Wengier,

yes this Updated sdl2 works with `MOUNT` and spaces thanks for that 👍 🥇 

I have renamed the Multiple CD Images to Names without Spaces like `D:\Emulatoren-Spielearchiv\CD-Rom-Games-Archiv\MS-DOS\Wing-Commander-Privateer-2\Privateer2-CD1.cue`

This works now too

Thanks for the Help and support

**Comment by Wengier** [comment]
This should work now. Closing.

**Comment by Starfoxfs** [comment]
Hi,
The problem is back in dosbox-x version 2023.10.06 or in earlier versions (2022). 
I hadn't used Dosbox-X since the beginning of 2022 so I don't know when the problem came back. 

Needs to be fixed again

Launchbox 13.8 sends the Imgmount command as follows:
`IMGMOUNT E 'D:\Test.cue' `

The launchbox command cannot be changed either

In Dosbox-X the IMGMOUNT command only works with aphostrophe " or without anything, but not with '
