### ISSUE TITLE
Building from source, build script cannot find SDL2 on my machine

### ISSUE THREAD

**Issue by brunocastello** [joncampbell123/dosbox-x#3433]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

macOS Monterey latest version

### What version(s) of DOSBox-X have this bug?

Latest code + Pull Request 3428

### Describe the bug

While building with script `build-macosx-sdl2` :

checking for sdl-config... no
checking for SDL - version >= 1.2.0... configure: error: SDL 1.x or SDL 2.x is required to compile this program

I can confirm that I have SDL2 installed on my Mac from brew, version 2.0.20, latest. However the build script can't find it? I may have to edit the script to point it to where SDL2 is?

### Expected behavior

Build successfully a binary.

### Steps to reproduce the behaviour

Clone the repo, fetch the pull request 3428, and proceed to try and compile from build-macosx-sdl2 script.

**Comment by Wengier** [comment]
I think the build-macosx-sdl2 script does try to compile the builtin SDL2 library. How about try the automated DOSBox-X builds here:

https://github.com/joncampbell123/dosbox-x/actions

**Comment by brunocastello** [comment]
Lst night in my test (not the automated builds yet) the build script did use the built in version of SDL2, but the version I already had installed was not detected before. I am trying to determine if the SDL version has something to do with my sound issues or not

**Comment by Jookia** [comment]
Could you dump your config.log and also location of SDL homebrew files?

**Comment by brunocastello** [comment]
[config.log](https://github.com/joncampbell123/dosbox-x/files/8603184/config.log)

@Jookia there you go:

Location of SDL homebrew files:

`MacBruno-Air:~ bruninho$ brew --prefix sdl2`
`/opt/homebrew/opt/sdl2`

**Comment by brunocastello** [comment]
@Jookia list of files:

[list.txt](https://github.com/joncampbell123/dosbox-x/files/8603292/list.txt)

following the output of the list, `/opt/homebrew/opt/sdl2` is a symlink it seems.

sdl2-config appears to be a program. I just ran it to say the version number as seen in my previous comment.

**Comment by Jookia** [comment]
The config.log you've posted seems to imply if found SDL2 properly:

```
configure:8280: checking for sdl2-config
configure:8303: found vs/sdl2/linux-host/bin/sdl2-config
configure:8316: result: vs/sdl2/linux-host/bin/sdl2-config
configure:8325: checking for SDL2 - version >= 2.0.5

...

SDL2_CFLAGS='-I/Users/bruninho/mydosboxx/dosbox-x/vs/sdl2/linux-host/include/SDL2 -D_THREAD_SAFE'
SDL2_CONFIG='vs/sdl2/linux-host/bin/sdl2-config'
SDL2_LIBS='-L/Users/bruninho/mydosboxx/dosbox-x/vs/sdl2/linux-host/lib -lSDL2 -lm -liconv -Wl,-framework,CoreAudio -Wl,-framework,AudioToolbox -Wl,-framework,ForceFeedback -lobjc -Wl,-framework,CoreVideo -Wl,-framework,Cocoa -Wl,-framework,Carbon -Wl,-framework,IOKit'
SDL_CFLAGS=''
SDL_CONFIG='no'
SDL_LIBS=''
```

**Comment by Jookia** [comment]
Could it be that this happens if you don't add --enable-sdl2 to the configure flags?

**Comment by Jookia** [comment]
I opened #3449 as a possible fix for this.

**Comment by brunocastello** [comment]
I think that build-macosx-sdl2 script does have —enable-sdl2 flag in configure?

**Comment by Jookia** [comment]
I think it compiles a bundled SDL2

**Comment by Jookia** [comment]
This should be fixed now, can you confirm?

**Comment by brunocastello** [comment]
Compiled a build right now.

> configure:8280: checking for sdl2-config
> configure:8303: found vs/sdl2/linux-host/bin/sdl2-config
> configure:8316: result: vs/sdl2/linux-host/bin/sdl2-config
> configure:8325: checking for SDL2 - version >= 2.0.5
> configure:8402: checking for sdl-config
> configure:8438: result: no
> configure:8447: checking for SDL - version >= 1.2.0
> configure:8582: checking for target cpu type
> configure:8643: result: ARMv8 Little Endian 64-bit
> configure:8692: checking for ALSA CFLAGS
> configure:8698: result: 

Doesn't seem to be fixed. It's still not getting the SDL2 version I have installed from brew (2.0.22).
[config.log](https://github.com/joncampbell123/dosbox-x/files/8644910/config.log)

**Comment by Jookia** [comment]
Thanks for the log, from what I can see it works. The text is misleading
but it's not actually reporting the version but saying what version it's
after, in this case 2.0.5 or newer.

The config.log shows that it does set C_SDL2.

Does it build and give SDL2 output?
