### ISSUE TITLE
Consolidate DosBox-X Version to one string, Windows and Linux, startup screen and titlebar

### ISSUE THREAD

**Issue by WarlockSVG** [joncampbell123/dosbox-x#409]
It is something small... more like a detail. It probably slipped your mind to update the version NR and release date. DosBox-X For windows doesn't show the version NR on the title bar... this would be nice ( it's something dosbox does ;-) ) ( screenshots ar from dosbox-x-windows-20171223-1017.zip release )
![sshot-76](https://user-images.githubusercontent.com/33853101/34322412-f57f6cf8-e826-11e7-9bc0-567bff120b4d.png)
![sshot-77](https://user-images.githubusercontent.com/33853101/34322413-f5992904-e826-11e7-9390-6c482a5dafe4.png)

**Comment by joncampbell123** [comment]
Fixed.

**Comment by WarlockSVG** [comment]
The version nr on the "first screen" slipt you mind. And you forgot to update the release date.

Also if you let DOSBox-X write the config file it uses "DOSBox" and not DOSBox-X "here and there"  ;-) ... this a really a detail. ( hope you don't mind me going into this kind of detail )

> This is the configuration file for DOSBox 0.82.1. (Please use the latest version of DOSBox)
> Lines starting with a # are comment lines and are ignored by DOSBox.
>        fullscreen: Start dosbox directly in fullscreen. (Press ALT-Enter to go back)
>        fulldouble: Use double buffering in fullscreen. It can reduce screen flickering, but it can also result in a slow DOSBox.
>        waitonerror: Wait before closing the console if dosbox has an error.
> ...

"first screen" ... dosbox-x 0.801
![sshot-60](https://user-images.githubusercontent.com/33853101/34358163-7d2d66c8-ea4d-11e7-9bbd-0f477113b1d9.png)

Release date is April 9, 2015
![sshot-61](https://user-images.githubusercontent.com/33853101/34358164-7d4e874a-ea4d-11e7-870c-ed8d90d23b3b.png)

**Comment by joncampbell123** [comment]
I get it, sorry.

**Comment by joncampbell123** [comment]
Working on it..

**Comment by joncampbell123** [comment]
Done

**Comment by WarlockSVG** [comment]
Nice :-)
