### ISSUE TITLE
Latest Intel macOS version crashes on start

### ISSUE THREAD

**Issue by Shrapnel21** [joncampbell123/dosbox-x#4438]
### Describe the bug

The latest x86 version for macOS crashed on start.
Seems it's looking for something ARM-related, although I'm no expert at all and can't be sure. Sorry. =(
Here's the crash report:

Process:               dosbox-x [2244]
Path:                  /private/var/folders/*/dosbox-x.app/Contents/MacOS/dosbox-x
Identifier:            com.dosbox-x
Version:               2023.09.01 (2023.09.01)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           dosbox-x [2244]
User ID:               501

Date/Time:             2023-09-02 13:40:40.596 +0200
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        E2DAB20E-07ED-8A95-C824-97B4344E85E3

Sleep/Wake UUID:       48ED6E7B-3F4D-4069-BD4D-54CCA46F898F

Time Awake Since Boot: 5100 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/arm64/libslirp.0.dylib
  Referenced from: /private/var/folders/*/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: image not found

Binary Images:
       0x10837a000 -        0x109562fff +com.dosbox-x (2023.09.01 - 2023.09.01) <46EEFB17-10FC-3655-9D5A-4EAE63C8C9EB> /var/folders/*/dosbox-x.app/Contents/MacOS/dosbox-x
       0x113eab000 -        0x113f3d267  dyld (750.7) <9F48F7F8-94D0-3793-99B7-DDEF657EF956> /usr/lib/dyld
    0x7fff2ccb8000 -     0x7fff2da76ffb  com.apple.AppKit (6.9 - 1894.70.110) <058D0F31-D353-36D9-83CD-1709EBB1390E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff2dac6000 -     0x7fff2dac6fff  com.apple.ApplicationServices (48 - 50) <A74C5919-EA2A-30FB-917E-09AAB26E96B0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff2ddf8000 -     0x7fff2ded9ff2  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <43014BB0-6604-3513-AB52-8D8577204FA6> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2dedb000 -     0x7fff2dedbfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <2FAE7F8D-2358-3B10-B47E-27B90B368557> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff2e67c000 -     0x7fff2e67cfff  com.apple.Carbon (160 - 162) <0C07A0EC-9474-3A5E-82A0-FD98B7C83BD8> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff2eb60000 -     0x7fff2eb60fff  com.apple.Cocoa (6.11 - 23) <9C7AC07A-7C05-37D4-910C-E9CDB239AFA8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff2ef4f000 -     0x7fff2f458ffb  com.apple.audio.CoreAudio (5.0 - 5.0) <47923B12-3D14-328A-9C86-27A3A2A73068> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2f9b0000 -     0x7fff2fe30ff9  com.apple.CoreFoundation (6.9 - 1678.104) <DFD82191-CCB6-3664-B803-5717036927AC> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3087b000 -     0x7fff308ccffe  com.apple.audio.midi.CoreMIDI (1.10 - 88) <9DC07E77-DA2B-3B25-939A-2BB8510CB957> /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
    0x7fff319c7000 -     0x7fff31a0bfff  com.apple.CoreVideo (1.8 - 0.0) <D35529AE-8740-320B-BB12-D1E60FDAB06B> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff3206f000 -     0x7fff32071ff3  com.apple.ForceFeedback (1.0.6 - 1.0.6) <9B324178-4FAA-3686-9E01-634607F38493> /System/Library/Frameworks/ForceFeedback.framework/Versions/A/ForceFeedback
    0x7fff327ab000 -     0x7fff3284fff3  com.apple.framework.IOKit (2.0.2 - 1726.148.1) <0A9D244C-AECC-3D29-86DE-4F3B04F8DD25> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff34f2d000 -     0x7fff34ff7fff  com.apple.Metal (212.8 - 212.8) <98C944D6-62C8-355E-90F8-C1CA2429EF24> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff3a369000 -     0x7fff3a378ff7  com.apple.opengl (17.10.22 - 17.10.22) <BCC1E523-1843-3FF8-8F7D-29DA67756434> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff3b336000 -     0x7fff3b5b9ffb  com.apple.QuartzCore (1.11 - 841.6) <DCD6050B-DB0E-3469-B18B-3DF3FAE77DEC> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff65a95000 -     0x7fff65a96fff  libSystem.B.dylib (1281.100.1) <5A20AE6C-BF4D-3689-B7D2-19F0721F6375> /usr/lib/libSystem.B.dylib
    0x7fff66870000 -     0x7fff66960fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff6727b000 -     0x7fff672aafff  libncurses.5.4.dylib (57) <995DFEEA-40F3-377F-B73D-D02AC59D591F> /usr/lib/libncurses.5.4.dylib
    0x7fff678f7000 -     0x7fff6792afde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff67944000 -     0x7fff6797afff  libpcap.A.dylib (89.120.2) <86DAA475-805A-3E01-86C5-6CAE4D1D9BC6> /usr/lib/libpcap.A.dylib

Model: iMac14,2, BootROM 433.140.2.0.0, 4 processors, Quad-Core Intel Core i5, 3,4 GHz, 16 GB, SMC 2.15f7
Graphics: kHW_NVidiaGeForceGTX775MItem, NVIDIA GeForce GTX 775M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.7)
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE SSD SD0128F, 121,33 GB
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Keyboard Hub
USB Device: Apple Keyboard
Thunderbolt Bus: iMac, Apple Inc., 23.10

### Steps to reproduce the behaviour

Just open the app, it crashes immediately.

### What operating system(s) this bug have occurred on?

macOS Catalina 10.15.7

### What version(s) of DOSBox-X have this bug?

2023.09.01 2023-09-01 17:00

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
At least no problem on Monterey. Both downloaded and one built myself.
![mac](https://github.com/joncampbell123/dosbox-x/assets/68574602/60cc005d-7cba-41ee-8289-ba741ecc932e)

**Comment by Shrapnel21** [comment]
This is quite weird, especially since I didn't have any problem up to the previous version and I didn't change anything on my system between one version and the other. =P

**Comment by maron2000** [comment]
Since the error clearly mentions that libslirp is missing, maybe worth try installing it?
I think `brew install libslirp` will do. (google homebrew for details if you have errors)
I usually build it myself instead of downloading the zip, so that maybe the difference.

**Comment by Shrapnel21** [comment]
Might that be a new requirement, though?
Because I've never even had Homebrew installed, just SDL 2 (updated to the latest version just yesterday, to make some more tests on DosBox-X and check if that was the problem).

**Comment by maron2000** [comment]
Actually, it shouldn't be a requirement, but maybe some problem in a particular build.
I want to see if the current executable requires you to install the library or not.
Or you may want to try the automated build (not the release version but build based on the same commit by github)
https://github.com/joncampbell123/dosbox-x/suites/15743310418/artifacts/898917829

**Comment by Shrapnel21** [comment]
Thanks for the heads up!
I tried the build you provided, but it just doesn't run.
No errors, nothing at all. System just says running the app is impossible.
This is getting weirder by the minute, but hey... thanks for your help!
Could it be something as simple and overlooked as DOSBox-X not supporting Catalina anymore, maybe?

**Comment by maron2000** [comment]
The last thing to try is to build DOSBox-X from source.
Automated build on github is built on Monterey so there may be compatibility issues between Catalina.

**Comment by Shrapnel21** [comment]
I'll try, thanks again! =)

**Comment by DominusExult** [comment]
the last version is clearly not built/packaged correctly.
otool -L reports on the x86-64 version:

```
@executable_path/arm64/libslirp.0.dylib (compatibility version 0.0.0, current version 0.0.0)
@executable_path/arm64/libglib-2.0.0.dylib (compatibility version 7401.0.0, current version 7401.4.0)
@executable_path/arm64/libintl.8.dylib (compatibility version 12.0.0, current version 12.0.0)
@executable_path/arm64/libfluidsynth.3.dylib
```
these are not bundled and also not in the x86_64 folder where they should be

**Comment by DominusExult** [comment]
You can solve this by downloading the previous release and copying the dylibs to both the arm64 and x86_64 subfolders of dosbox-x.app/contents/macos

**Comment by maron2000** [comment]
@DominusExult How about the link I showed above?
The current Release is built by @joncampbell123 and we can see if automated builds have such problems as well.

**Comment by Shrapnel21** [comment]
> You can solve this by downloading the previous release and copying the dylibs to both the arm64 and x86_64 subfolders of dosbox-x.app/contents/macos

Works by doing this.
While copying the libs I found out that the x86_64 folder inside the app is empty in the latest version, there were no libs at all there.

**Comment by DominusExult** [comment]
> @DominusExult How about the link I showed above?
> The current Release is built by @joncampbell123 and we can see if automated builds have such problems as well.

Yes, same problem. In a way, even worse as it doesn't even have the subfolders for the arches :)

So to recap:
- the dylib's aren't packaged
- the dylib's are linked wrong for x86_64 (to @executable_path/arm64/ instead of @executable_path/x86_64/), only the dependencies of the libs are correctly linked)

**Comment by emendelson** [comment]
`brew install libslirp` and then building worked me...

**Comment by DominusExult** [comment]
It's not about building, it's that the download binary release is missing the dylibs

**Comment by emendelson** [comment]
I know! I only posted in case someone needs a working app right now...

**Comment by emendelson** [comment]
I think I've found the problem, but I've only found part of the solution.

In the file `appbundledeps.py` line 131 uses the address of brew files on ARM system, `opt`. If you're building under Intel, then change the line so it reads:

`   if re.match(r"^/usr/local/",deppath):`

Now run `make dosbox-x.app`. The resulting file has some dylibs in the x86_64 folder, but the app won't run if you tell brew to remove libslirp. What you need to do is copy the files in the x86_64 folder into the arm64 folder, and the resulting app will run on a clean system (one that does not have brew installed).

My guess is that something needs to be fixed in makefile.in or something else that creates the makefile, and of course that `appbundledeps.py` needs to be revised to work with both architectures. But I'm not expert enough to do this myself, unfortunately.

**Comment by emendelson** [comment]
I've put together a universal SDL2 build that works around the issues described here:

https://github.com/joncampbell123/dosbox-x/discussions/4465

**Comment by maron2000** [comment]
@emendelson Can you elaborate the actual command you used for macdylibbundler?
I want to try if I can include that in the automated builds.

**Comment by emendelson** [comment]
@maron2000 - Here it is. As you'll see, I had to change the string `arm` to `intel` when doing the same thing on my Intel build on an Intel machine:

`dylibbundler -od -b -x /Users/edward/Desktop/DOSBox-X-ARM.app/Contents/MacOS/dosbox-x -d /Users/edward/Desktop/DOSBox-X-ARM.app/Contents/libs-arm/ -p @executable_path/../libs-arm/`

I simply copied it from one of the examples on the macdylibsbundler page, changing the file paths, and it worked. It would be excellent if this could be part of the automated bundle.

**Comment by derRichter** [comment]
i can confirm this problem, the x64 version is compiled to search for aarch64-libs also in the path is not my username, there is USER hardcoded?
i tested this on big sure x64

On first start you got the error that the libs cant loaded:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 3694F5E4-3E85-3CD5-A2B0-534E2DFC1355
Library not loaded: @executable_path/arm64/libslirp.0.dylib
  Referenced from: /Users/USER/Downloads/*/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: image not found
```
in path is USER and arm64 wrong


After copy both ob the lib-folders x64 and arm64 (i know this is wrong), i got the error for wrong arch, but this is logical, but the app looking for the wrong libs:

```
Termination Reason:    DYLD, [0x2] Wrong architecture

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/arm64/libslirp.0.dylib
  Referenced from: /Users/USER/Downloads/*/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: no suitable image found.  Did find:
	/Users/derRichter/Downloads/dosbox-x-macosx-x86_64-20230901155520/dosbox-x/dosbox-x.app/Contents/MacOS/arm64/libslirp.0.dylib: mach-o, but wrong architecture
	/Users/derRichter/Downloads/dosbox-x-macosx-x86_64-20230901155520/dosbox-x/dosbox-x.app/Contents/MacOS/arm64/libslirp.0.dylib: mach-o, but wrong architecture
```

**Comment by maron2000** [comment]
I amended the automated Intel macOS build to include the following libraries to arm64 directory, which the executable expects.
Can you test whether it works?
https://github.com/maron2000/dosbox-x-1/actions/runs/6437587737
```
@executable_path/arm64/libSDL_net-1.2.0.dylib (compatibility version 9.0.0, current version 9.0.0)
@executable_path/arm64/libslirp.0.dylib (compatibility version 0.0.0, current version 0.0.0)
@executable_path/arm64/libglib-2.0.0.dylib (compatibility version 7601.0.0, current version 7601.4.0)
@executable_path/arm64/libintl.8.dylib (compatibility version 12.0.0, current version 12.0.0)
@executable_path/arm64/libfluidsynth.3.dylib (compatibility version 3.0.0, current version 3.2.1)
```

**Comment by emendelson** [comment]
The SDL1 version (I'll report on SDL2 in a moment) doesn't have any libraries in the Intel folder, and won't start, with this:

```
/Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x/dosbox-x.app/Contents/MacOS/dosbox-x ; exit;
dyld[97377]: Library not loaded: @executable_path/arm64/libfluidsynth.3.dylib
  Referenced from: <F18E0690-71FC-385C-9D0F-B22C6B4A028A> /Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: tried: '/Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x/dosbox-x.app/Contents/MacOS/arm64/libfluidsynth.3.dylib' (no such file), '/usr/local/lib/libfluidsynth.3.dylib' (no such file), '/usr/lib/libfluidsynth.3.dylib' (no such file, not in dyld cache)
zsh: abort      
```
The SDL2 version also fails:
```
edward@Edwards-MBP-Sonoma MacOS % ./dosbox-x
dyld[97631]: Library not loaded: @executable_path/arm64/libfluidsynth.3.dylib
  Referenced from: <247361C4-1D60-38B5-9248-22FC5AEE8846> /Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: tried: '/Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/arm64/libfluidsynth.3.dylib' (no such file), '/usr/local/lib/libfluidsynth.3.dylib' (no such file), '/usr/lib/libfluidsynth.3.dylib' (no such file, not in dyld cache)
zsh: abort      ./dosbox-x
```
SDL2 also has no libraries in the x86_64 folder.

What I don't understand is that the fluid synth library does seem to be where it's supposed to be. But maybe I simply don't understand.

**Comment by maron2000** [comment]
@emendelson 
Thanks for testing. A fix is on the way.
Meanwhile, can you rename the following files to `libfluidsynth.3.dylib` and see if it can run?
```
/Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x/dosbox-x.app/Contents/MacOS/arm64/libfluidsynth.3.2.1.dylib
/Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/arm64/libfluidsynth.3.2.1.dylib
```

**Comment by emendelson** [comment]
@maron2000 - I should have reported that I tried that already. It gets even worse:

```
dyld[2291]: Library not loaded: /usr/local/opt/sdl12-compat/lib/libSDL-1.2.0.dylib
  Referenced from: <77957A24-7557-364D-896F-70B3E97BB67A> /Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/arm64/libSDL_net-1.2.0.dylib
  Reason: tried: '/usr/local/opt/sdl12-compat/lib/libSDL-1.2.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/sdl12-compat/lib/libSDL-1.2.0.dylib' (no such file), '/usr/local/opt/sdl12-compat/lib/libSDL-1.2.0.dylib' (no such file), '/usr/local/lib/libSDL-1.2.0.dylib' (no such file), '/usr/lib/libSDL-1.2.0.dylib' (no such file, not in dyld cache)Library not loaded: /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: <33A5CCCE-B60B-328F-AF10-50DC41466BEE> /Users/edward/Downloads/dosbox-x-macosx-x86_64-20231007000221-2/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/arm64/libfluidsynth.3.dylib
  Reason: tried: '/usr/local/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/usr/local/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/usr/local/lib/libgthread-2.0.0.dylib' (no such file), '/usr/lib/libgthread-2.0.0.dylib' (no such file, not in dyld cache)
```

**Comment by maron2000** [comment]
@emendelson 
Thank you for sharing your information.
My personal builds are working without the files included in your log, or the location is different, so the problem seems to be much more complicated than I imagined.

**Comment by emendelson** [comment]
@maron2000 - I would be happy to try out your code if you ever want someone to test it. Is your version posted anywhere?

**Comment by joncampbell123** [comment]
> @maron2000 - I would be happy to try out your code if you ever want someone to test it. Is your version of the source code posted anywhere?
> 
> EDIT: I think a build needs to have all the libraries that are included in the release version. Maybe not all are needed, but that seems safe. The build you offered only had a few of those libraries.

Last night while building, I caught that the Intel Mac OS builds did not copy in the required libraries, which I fixed. Hopefully the latest build I put up for Intel Macbooks should work properly.

**Comment by Shrapnel21** [comment]
Downloaded the latest published build from 12 hours ago, still doesn't open on Intel.
Running on macOS 10.15.7, this is what I get:

Process:               dosbox-x [3733]
Path:                  /private/var/folders/*/dosbox-x.app/Contents/MacOS/dosbox-x
Identifier:            com.dosbox-x
Version:               2023.10.06 (2023.10.06)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           dosbox-x [3733]
User ID:               501

Date/Time:             2023-10-07 20:36:13.209 +0200
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        E2DAB20E-07ED-8A95-C824-97B4344E85E3

Sleep/Wake UUID:       4FCEB3E0-297D-4790-86F1-41F5E50B8C19

Time Awake Since Boot: 21000 seconds
Time Since Wake:       720 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/arm64/libavcodec.60.dylib
  Referenced from: /private/var/folders/*/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: image not found

Binary Images:
       0x104a66000 -        0x105ce3fff +com.dosbox-x (2023.10.06 - 2023.10.06) <A8D9E01A-E568-33F0-A821-6DA1A3225BBE> /var/folders/*/dosbox-x.app/Contents/MacOS/dosbox-x
       0x10f179000 -        0x10f20b267  dyld (750.7) <9F48F7F8-94D0-3793-99B7-DDEF657EF956> /usr/lib/dyld

Model: iMac14,2, BootROM 433.140.2.0.0, 4 processors, Quad-Core Intel Core i5, 3,4 GHz, 16 GB, SMC 2.15f7
Graphics: kHW_NVidiaGeForceGTX775MItem, NVIDIA GeForce GTX 775M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.7)
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE SSD SD0128F, 121,33 GB
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Keyboard Hub
USB Device: Apple Keyboard
Thunderbolt Bus: iMac, Apple Inc., 23.10

**Comment by maron2000** [comment]
I think commit f719635 is quite close to conclusion.
The libraries are copied to x86_64 directory but the binary expects it to be arm64 regardless of target platform.

**Comment by emendelson** [comment]
@maron2000 - Yes, I built the latest code, and `make dosbox-x.app` produced a working app.

**Comment by maron2000** [comment]
@emendelson Yes, I only have Intel mac so I can't test arm versions.
Are the arm versions working OK now?

**Comment by emendelson** [comment]
@maron2000 - Yes, the arm version works OK with the latest commit.

**Comment by PatDal81** [comment]
Same problem, different output when testing it on my Intel MBP: 

dyld[57465]: Library not loaded: @executable_path/arm64/libslirp.0.dylib
  Referenced from: <A8D9E01A-E568-33F0-A821-6DA1A3225BBE> /Applications/dosbox-x.app/Contents/MacOS/dosbox-x
  Reason: tried: '/Applications/dosbox-x.app/Contents/MacOS/arm64/libslirp.0.dylib' (no such file), '/usr/local/lib/libslirp.0.dylib' (no such file), '/usr/lib/libslirp.0.dylib' (no such file, not in dyld cache)
[1]    57465 abort      ./dosbox-x

Hope it helps.  Been 2 version behind since this bug.

**Comment by maron2000** [comment]
Fixed the link to the attached dynamic libraries for the Intel builds.
I think it should not break arm mac builds.

**Comment by yochenhsieh** [comment]
The latest build on 20240102 still crashes on mac os x 12.7.2
<img width="383" alt="截圖 2024-01-03 上午10 52 28" src="https://github.com/joncampbell123/dosbox-x/assets/1897377/2604b459-25cc-40c9-a602-7058f63cf798">

Both sdl and sdl2 version failed to load SDL2 library.

**Comment by maron2000** [comment]
Nightly builds are built with SDLnet library installed via homebrew, which requires SDL2 to be installed as well.
I don't know why it doesn't use the in-tree SDLnet, so maybe worth trying using the in-tree version.

You can try the build from my repository.
https://github.com/maron2000/dosbox-x-1/actions/runs/7406918500

![sdlfix](https://github.com/joncampbell123/dosbox-x/assets/68574602/124dcb0e-39f9-45b3-99bd-27cc18f19614)

**Comment by yochenhsieh** [comment]
Confirmed your build is working!

**Comment by maron2000** [comment]
@yochenhsieh 
Thanks for testing. I'll make a PR.
