### ISSUE TITLE
Hercules cannot change to amber/white with CTRL+F7 after 2023.03.31

### ISSUE THREAD

**Issue by thec0n** [joncampbell123/dosbox-x#5842]
### Describe the bug

Problem might have to do with this (now solved) or not:

https://github.com/joncampbell123/dosbox-x/issues/5064

But, after 2023.03.31 (working), CTRL+F7 stopped working to toggle amber/white/green shade in Hercules monochrome mode in DosBox-X. Although CTRL+F7 still works in text mode for all versions (i.e. the start of DosBox-X), when you load a game in hercules graphics mode, CTRL+F7 toggle stops working (stays in Green monochrome shade).

Tested in:
2023.03.31 (working)
2023.05.01 (not working)
2023.09.01 (not working)
2023.10.06 (not working)
2025.05.03 (still not working).

### Steps to reproduce the behaviour

Just load a game in hercules monochrome graphics mode. Toggle CTRL+F7 stops working to toggle amber/green/white.

### Expected behavior

Toggle works (green/amber/white).

### What operating system(s) this bug have occurred on?

Windows 11 24H2

### What version(s) of DOSBox-X have this bug?

2023.05.01 and onwards

### Used configuration

```ini

```

### Output log

```text

```

### Have you checked that no similar bug report(s) exist?

- [x] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Fixed.

**Comment by thec0n** [comment]
Reporting not fixed completely in dosbox-x-vsbuild-win32-20251007154914\bin\Win32\Release\

Before any game, CTRL+F7 cycles colors (good)
CTRL+F8 does nothing (good, because not in graphics mode yet).

====Ignore ON====
After the game has loaded, if CTRL+F8 is activated (blend mode on), pressing CTRL+F7 creates problems, after which CF8 cycles problematically. When you press CF8 to remove blend mode, then CF7 to cycle colors, only then you can still go safely to CF8.

Will post more details in a few hours.
====Ignore OFF====

Clarification: CTRL+F7 cycles colors only if CTRL+F8 is not in blend mode (otherwise it doesn't do anything). Also, when in blend mode on (with CTRL+F8), that mode is always in green. Also, when blend mode is on, CTRL+F7 does not work. You need to first disable green blend mode (CTRL+F8), then change colors. As a conclusion, you can never have blend mode in other colors other than green, because CTRL+F8 always blends in Green.

What we need is CTRL+F7 interactively change palette, regardless of blend mode on or off. i.e. if we are in white blend mode off, CTRL+F8 should enable white blend mode. If we are in amber blend mode on, pressing CTRL+F7 should cycle palette (but with blend mode always on).
