### ISSUE TITLE
The Playroom - Crashes on Tandy when launched thorugh playroom.exe

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#5865]
### Describe the bug

Game crashes when running playroom.exe
Running via playtdy.exe works fine

### Steps to reproduce the behaviour

Load playroom.exe

### Expected behavior

Game loads correctly

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

Latest Stable

### Used configuration

```ini

```

### Output log

```text

```

### Additional information

<img width="1520" height="1960" alt="Image" src="https://github.com/user-attachments/assets/8b381113-7e1e-4fb0-a178-f2131d4332bb" />

### Have you checked that no similar bug report(s) exist?

- [x] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
The EGA version also crashes with an MCB corruption error if run the same.

**Comment by joncampbell123** [comment]
Uh, at one point when it calls INT 21h AH=3Dh to load SETUP.DAT, the stack pointer is positioned just so that it overlaps the MCB block of the large free block it just opened up earlier.

The MCB is corrupted by the stack on return from INT 21h.

The program has put the stack pointer in a very precarious place.

Maybe this is one of those cases where if the MCB chain is broken, and it follows the program PSP, it just creates another one. Especially since the MCB trashed was just freed. I'll run it from an MS-DOS boot disk and see what happens.

**Comment by joncampbell123** [comment]
It causes the same MCB broken chain condition after INT 21h AH=3Dh under real MS-DOS 5.0 as it does in DOSBox-X.

**Comment by joncampbell123** [comment]
The difference is that, instead of halting with an error, MS-DOS just sort of scans up to the end of the last block and creates a new free block, and then EXEC can load properly.

**Comment by joncampbell123** [comment]
```
MS-DOS

PLAYROOM.EXE

MCB Seg  Size (bytes)  PSP Seg (notes)  Filename
Conventional memory:
   0253          4496     0008 (DOS)    SDػ^C&
   036D            64     0008 (DOS)    SC^P&~@=
   0372          2368     0373          COMMAND
   0407            64     0000 (free)   paramete
   040C           256     0373           value n
   041D            80     0424           handle^_
   0423        638400     0424          PLAYROOM

INT 21h AH=4Ah

MCB Seg  Size (bytes)  PSP Seg (notes)  Filename
Conventional memory:
   0253          4496     0008 (DOS)    SDػ^C&
   036D            64     0008 (DOS)    SC^P&~@=
   0372          2368     0373          COMMAND
   0407            64     0000 (free)   paramete
   040C           256     0373           value n
   041D            80     0424           handle^_
   0423          2304     0424          PLAYROOM
   04B4        636080     0000 (free)   $^D^E5^D^Fr

...

MCB Seg  Size (bytes)  PSP Seg (notes)  Filename
Conventional memory:
   0253          4496     0008 (DOS)    SDػ^C&
   036D            64     0008 (DOS)    SC^P&~@=
   0372          2368     0373          COMMAND
   0407            64     0000 (free)   paramete
   040C           256     0373           value n
   041D            80     0424           handle^_
   0423          2304     0424          PLAYROOM
   04B4        636080     0000 (free)   $^D^E5^D^O^F

INT 21h AH=3Dh SETUP.DAT

Conventional memory:
   0253          4496     0008 (DOS)    SDػ^C&
   036D            64     0008 (DOS)    SC^P&~@=
   0372          2368     0373          COMMAND
   0407            64     0000 (free)   paramete
   040C           256     0373           value n
   041D            80     0424           handle^_
   0423          2304     0424          PLAYROOM
   (data addr 0435:0246 is 854 bytes past this MCB)
MCB chain broken at 04B4:0000!

INT 21h AH=4Bh EXEC. Within INT 21h, it auto-heals the MCB apparently.

MCB Seg  Size (bytes)  PSP Seg (notes)  Filename
Conventional memory:
   0253          4496     0008 (DOS)    SDػ^C&
   036D            64     0008 (DOS)    SC^P&~@=
   0372          2368     0373          COMMAND
   0407            64     0000 (free)   paramete
   040C           256     0373           value n
   041D            80     0424           handle^_
   0423          2304     0424          PLAYROOM
   (data addr 0435:06A2 is 1970 bytes past this MCB)
   04B4        636080     0000 (free)   5^D}^F5^DFr

PLAYEGA loaded:

MCB Seg  Size (bytes)  PSP Seg (notes)  Filename
Conventional memory:
   0253          4496     0008 (DOS)    SDػ^C&
   036D            64     0008 (DOS)    SC^P&~@=
   0372          2368     0373          COMMAND
   0407            64     04B5          paramete
   040C           256     0373           value n
   041D            80     0424           handle^_
   0423          2304     0424          PLAYROOM
   (data addr 0435:06A2 is 1970 bytes past this MCB)
   04B4        124784     04B5          playega
   232C        511280     0000 (free)
```

**Comment by joncampbell123** [comment]
Fixed.

When running PLAYROOM, make sure you disable xms, ems, and umb, or run LOADFIX -a before running PLAYROOM.EXE.

**Comment by ualaa1** [comment]
It still doesn't load properly on Tandy. Please reopen. Apologies for the screenshot, but I didn't have access to my computer and had to use someone else's. I used a pure disk version on https://archive.org/details/20240119_20240119_0659 and attached the 720kb version on drive A

<img width="640" height="400" alt="Image" src="https://github.com/user-attachments/assets/ecebd9f3-7872-4477-a656-71d8587141c5" />

**Comment by joncampbell123** [comment]
OK.

**Comment by joncampbell123** [comment]
I can get all versions to run from PLAYROOM as follows:

```
[dosbox]
machine=tandy

[dos]
mcb corruption becomes application free memory=true

[autoexec]
loadfix -a
imgmount a: "Playroom, The (1989) (v1.0) (720K) [cr].ima" -t floppy
a:
playroom
```

The mcb corruption option is necessary to instruct DOSBox-X to ignore and reconstruct a free memory block when PLAYROOM corrupts the MCB with it's stack and then calls DOS to run the program.

LOADFIX -a is needed to avoid crashes.

**Comment by ualaa1** [comment]
Works with your settings
