### ISSUE TITLE
OSX compilation error, graphics glitch

### ISSUE THREAD

**Issue by Jarvik7** [joncampbell123/dosbox-x#59]
It looks like the recent work on the cpus has broken compilation on OS X (Yosemite, Xcode 6.2)

`core_normal_8086.cpp:50:25: error: use of undeclared identifier 'val'`
`return (mem_readb(off,val) | (mem_readb(off-0xffff) << 8));`

`dos_tables.cpp:100:3: error: no matching function for call to object of type 'LOG'`
` LOG(LOG_DOSMISC,LOG_ERROR)("DOS_GetMemory(%u) failed for '%s' (alloc=0x%04x segment=0x%04x end=0x%04x)\n",`

`dos_tables.cpp:105:2: error: no matching function for call to object of type 'LOG'`
       `LOG(LOG_DOSMISC,LOG_DEBUG)("DOS_GetMemory(0x%04x pages,\"%s\") = 0x%04x\n",pages,who,page);`

`bios.cpp:277:2: error: no matching function for call to object of type 'LOG'`
`LOG(LOG_BIOS,LOG_DEBUG)("ROMBIOS_GetMemory(0x%05x bytes,\"%s\",align=%u,mustbe=0x%05x) = FAILED\n",(int)bytes,who,(int)alignment,(int)must_be_at);`

Deleting the var argument in the first error and commenting out the LOG() calls results in a working binary. I've pushed it to the OS X branch of my fork.

**Comment by Jarvik7** [comment]
Here is the graphics glitch. Everything is blue. All settings are default.
![screen shot 2015-04-08 at 20 17 43](https://cloud.githubusercontent.com/assets/6679920/7044265/764e4212-de2c-11e4-8a3a-9934ce9aacba.png)
![screen shot 2015-04-08 at 20 15 39](https://cloud.githubusercontent.com/assets/6679920/7044264/764a1408-de2c-11e4-97a6-4920f0e76d9b.png)

**Comment by joncampbell123** [comment]
Here's what I know about the SDL library: You can set the video mode to certain bits per pixel but whether the pixels are ARGB or XRGB or XBGR or whatever is determined by the system, SDL doesn't convert that part for you.

In the XRGB output code I've written my code always makes sure to write the 0xFF in the X/A channel, which OS X has mapped to blue. The normally bright green "welcome to DOSBox" text is red, the normally red "ctrl-F11" text is cyan.

The fix as I understand it is that when DOSBox-X sets the SDL video mode it needs to read back from the SDL library what the RGB channel bit order is and use it properly.

**Comment by joncampbell123** [comment]
For the compile bug, I saw the same errors come up once I stopped building with C_DEBUG. I fixed it in the latest commit by unifying how the LOG class is defined. I have no idea why the LOG class was defined one way for C_DEBUG and another way for non-debug builds, but it's completely unnecessary.

**Comment by joncampbell123** [comment]
The latest code contains debug statements that print out your RGBA mapping. Run dosbox in full debug mode like this and make sure your dosbox.conf refers to a log file:

dosbox -debug

**Comment by Jarvik7** [comment]
Recompiled the latest build last night.
This error still happens:
`core_normal_8086.cpp:50:25: error: use of undeclared identifier 'val'`
`return (mem_readb(off,val) | (mem_readb(off-0xffff) << 8));`

Simply deleting the "val" argument fixes compilation.

Did not see your comment on how to enable the full debug logging so I will have to report back tonight on RGBA mapping.

**Comment by joncampbell123** [comment]
Ah, got it.

**Comment by Jarvik7** [comment]
By the way, is there an up to date .conf template for -x somewhere?
Maybe the "save config" option should spew out a full .conf with all current settings instead of an empty file when everything is default.

**Comment by joncampbell123** [comment]
I already have it coded to spew a full .conf if you use the -all switch. Like this:

config -all -wc dosbox.conf

**Comment by Jarvik7** [comment]
Thanks, didn't know about that command.

**Comment by Jarvik7** [comment]
Weird, it set output=direct3d in the conf, which isn't a valid value (not listed in the comment and gives an error in the log). I guess that is the default though?

**Comment by Jarvik7** [comment]
OSBox LOG:       5358 DEBUG MISC:SDL video mode: 720x400 (clip 720x400 with upper-left at 0x0) 32bpp
DOSBox LOG:       5358 DEBUG MISC:   red: shift=8 mask=0x0000ff00
DOSBox LOG:       5358 DEBUG MISC:   green: shift=16 mask=0x00ff0000
DOSBox LOG:       5358 DEBUG MISC:   blue: shift=24 mask=0xff000000
DOSBox LOG:       5358 DEBUG MISC:   alpha: shift=0 mask=0x00000000

**Comment by joncampbell123** [comment]
Huh, that's what I thought.

There's plenty of code in vga_draw.cpp that assumes the topmost 8 bits are alpha channel (that I wrote) because most PC graphics cards always like to put the alpha or X channel there. Not sure why OS X would choose a layout like that.

**Comment by joncampbell123** [comment]
OK. Pushed a commit that uses the RGB bitmask values instead of assuming. Does that fix it?

It doesn't fix the possibility that the highcolor/truecolor VESA modes don't work, but it should fix the majority of VGA/EGA/CGA/Hercules/etc video mode emulations.

**Comment by Jarvik7** [comment]
Getting correct colors now. Don't know about VESA modes though.
