### ISSUE TITLE
PC-98: Grounseed only advances frames when you move the mouse

### ISSUE THREAD

**Issue by pedipanol** [joncampbell123/dosbox-x#665]
I start the game, the music for the team logo plays at the normal speed, but there's a black screen, if you move the mouse the logo appears and the frames will advancing (slowly) as you move it.
When you get to the Opening cutscene after that, it plays the first part just fine, then fade out into black (I suppose if I keep moving the mouse it'll get to the next part[?]), with the music still playing at normal speed.
After clicking to skip the opening and moving the mouse for a bit you get to the title screen, that apparently is at the normal speed, but when you start playing the game, the issue returns.

I thought it was something related to the mouse driver, but I couldn't find a way to disable the mouse input on DOSBOX-X and changing the mouse-related settings (except for the Internal Emulation option that doesn't seem to disable even after you save the settings) didn't work either

**Comment by yksoft1** [comment]
Falcom's Lord Monarch had a similar problem.

**Comment by joncampbell123** [comment]
Try:

int33=false

Also try:

pc-98 fm board irq=12

**Comment by joncampbell123** [comment]
See also: https://github.com/joncampbell123/dosbox-x/issues/609#issuecomment-382583880

**Comment by joncampbell123** [comment]
Are you running the latest commit of the code, or the latest binary, or...?

**Comment by pedipanol** [comment]
I'm running the latest binary

**Comment by joncampbell123** [comment]
Ah---That binary is a month old. Many fixes have been made since then.

Sounds like it's time to release the next binary release.

**Comment by joncampbell123** [comment]
@yksoft1 It seems a lot of games in my test collection suddenly have FM music if I set the FM board IRQ to IRQ 12. It seems that the best fix to these games is to change the default IRQ in DOSBox-X to IRQ 12 for FM rather than IRQ 3. Agree?

**Comment by joncampbell123** [comment]
Is there somewhere on the internet I can obtain this game?

**Comment by joncampbell123** [comment]
Please try the latest released binary, it may be related to problems that I've already fixed.

**Comment by pedipanol** [comment]
Oh, thanks for releasing a new version! I tried out and the game seems to be playable now!
But the problem persists at the opening animations persists (though it's not as slowly as last time)

**Comment by pedipanol** [comment]
Also, there's pc98-maker-betsu-tsumeawase on archive.org that is an archive of PC-98 games sorted by company name (with titles in japanese though), I'm not sure which game you want but both Grounseed and Lord Monarch are available over there
Grounseed is in the -su file and Lord Monarch in the -naninu one
