### ISSUE TITLE
machine=pcjr NMI keyboard handler uses CPU registers without saving contents

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#799]
Need to check it against DOSBox SVN and any IBM PCjr technical reference available.

**Comment by yksoft1** [comment]
I think my copy of King's Quest I doesn't run in machine=pcjr for now.

**Comment by joncampbell123** [comment]
Blank screen?

**Comment by yksoft1** [comment]
My copy of KQ1 crashes in machine=pcjr without LOADFIX, will run into title screen and either hang or crash with "Corrupt MCB" errors soon after enter game screen, with a lot of "ERROR CPU:Write ff to rom at e4e91" like in the log.

**Comment by yksoft1** [comment]
I tried a PCjr cartridge program ColorPaint and it sometimes had graphic glitches.
Also tried a PCjr cartridge game Pitfall II, and it hangs after game starts.

**Comment by joncampbell123** [comment]
I'm writing a basic video mode testing program for IBM PC/XT/AT mode (and real hardware).

https://github.com/joncampbell123/doslib/blob/master/test-fw/video/pc/test.c

If DOSBox-X/DOSBox SVN emulation of machine=pcjr is correct, the video at B800 is stuck as a 16KB mirror and to properly draw in the 320x200x16 and 640x200x4 Tandy/PCjr modes requires looking up in the BIOS the system memory that video memory is drawn from.

PCjr uses system memory as video memory, instead of the video hardware having it's own.

The DOSBox DOS kernel emulates PCjr MS-DOS behavior by allocating a fixed memory block at segment 0x1800 for PCjr video memory.

My test program does a quick test of the video RAM to make sure it reads and writes correctly, however it often fails for CGA mode 4 and PCjr 640x200x4 mode because some byte got flipped around somehow. Occasionally for no apparent reason, the MCB list gets corrupted. That's where this concern comes from.

**Comment by joncampbell123** [comment]
Update: I modded test.c to print EVERY byte that came back wrong, and 80x25 mono text, CGA mode 4, and 640x200x4 come back as if at some point some remapping happened to cause the test to fail.

Looking further at the report, the dump of all bytes shows that for some reason, video RAM came back as if repeating every 4KB instead.

Example:

WARN> VRAM TEST FAILED, data written did not read back at byte offset 0xfb3, 3d want 7c
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0xfb4, 7a want bb
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0xfb5, bb want fa
...
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x1fb3, 3d want 7c
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x1fb4, 7a want bb
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x1fb5, bb want fa
...
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x2fb3, 3d want 7c
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x2fb4, 7a want bb
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x2fb5, bb want fa
...
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x3fb3, 3d want 7c
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x3fb4, 7a want bb
WARN> VRAM TEST FAILED, data written did not read back at byte offset 0x3fb5, bb want fa

That might explain the visible glitches in some games.

**Comment by joncampbell123** [comment]
DOSBox SVN emulation of machine=pcjr doesn't seem to have this problem, so it seems to have been fixed upstream already. I'll look at what they fixed.

**Comment by joncampbell123** [comment]
Hold on...

None of these glitches happen unless I press keys on the keyboard during the test to hurry it along.

Keyboard input seems to cause the corruption. Letting the test run without touching the keyboard seems to fix the glitches and errors.

Could this be related to my attempt to emulate the NMI keyboard interrupt of the PCjr?

**Comment by joncampbell123** [comment]
In fact, I just noticed that the NMI keyboard interrupt handler is CB_IRET (which doesn't save any registers) yet the callback handler calls IRQ1_Handler() which does modify registers.

So this is not a memory corruption issue, this is an issue with a keyboard interrupt handler using CPU registers without saving them.

**Comment by joncampbell123** [comment]
Fixed.

@yksoft1 Can you confirm the fix on your end with King's Quest? I don't have a copy to test at the moment.

**Comment by yksoft1** [comment]
No crashes in the DOS version and PCjr booter version of KQ1 anymore, but graphical glitches still there.
ColorPaint seems to be working now.
Still cannot move character in Pitfall II.
